/** Account dashboard copy. */
export const account = {
  greeting: "Živjo",
  rows: {
    orders: "Moja naročila",
    details: "Moji podatki",
    support: "Kontaktirajte podporo",
    logout: "Odjava",
  },
  orders: {
    title: "Moja naročila",
    empty: "Še nimate naročil — vaše prvo vas čaka v trgovini.",
    showMore: "Pokaži več",
    showLess: "Pokaži manj",
    shippedWith: "Odposlano z",
    detailLink: "Podrobnosti naročila",
    reviewCta: "Ocenite izdelek",
    reviewed: "Ocenjeno ✓",
    /** An unpaid order can be paid from the account; the confirmation page resumes the payment (QA M10). */
    payNow: "Dokončaj plačilo",
    unpaidNotice: "To naročilo še ni plačano. Plačilo lahko dokončate ali pa naročilo prezrete — brez plačila ga ne odpremimo.",
  },
  /** Customer-facing wording, the same as /sledi and the mails: PENDING waits for money, PROCESSING is being handled (QA M10). */
  statuses: {
    PENDING: "Čaka na plačilo",
    PAID: "Plačano",
    PROCESSING: "V obdelavi",
    SHIPPED: "Odposlano",
    DELIVERED: "Dostavljeno",
    CANCELLED: "Preklicano",
    REFUNDED: "Vrnjeno",
  } as const,
  detail: {
    back: "← Nazaj na naročila",
    lines: "Postavke",
    totals: "Zneski",
    subtotal: "Vmesna vsota",
    discount: "Popust",
    shipping: "Dostava",
    total: "Skupaj",
    addresses: "Naslovi",
    shippingAddress: "Naslov za dostavo",
    billingAddress: "Naslov za račun",
    payment: "Plačilo",
    paymentMethods: { stripe: "Kartica / Apple Pay / Google Pay", paypal: "PayPal", test: "Testno plačilo" },
    vat: "Vključen DDV",
    invoice: "Prenesi račun (PDF)",
    tracking: "Sledenje pošiljke",
    statusLabel: "Status",
    notes: "Sporočila trgovine",
  },
  addresses: {
    title: "Moji podatki",
    book: "Adresar",
    add: "Dodaj naslov",
    edit: "Uredi",
    delete: "Izbriši",
    setDefault: "Nastavi kot privzeti",
    default: "Privzeti",
    fullName: "Ime in priimek",
    line1: "Ulica in hišna številka",
    line2: "Dopolnilo (neobvezno)",
    postalCode: "Poštna številka",
    city: "Kraj",
    country: "Država",
    phone: "Telefon",
    label: "Oznaka (npr. Dom, Služba)",
    save: "Shrani naslov",
    saved: "Naslov shranjen.",
    empty: "Adresar je prazen.",
    marketing: "Prejemanje e-novic",
    marketingSaved: "Nastavitve shranjene.",
    profileTitle: "Profil",
    cancel: "Prekliči",
    invalid: "Preverite naslov in obliko poštne številke za izbrano državo.",
    invalidPhone: "Vnesite veljavno telefonsko številko — samo številke, presledki in znak +.",
    invalidPostalCode: "Preverite obliko poštne številke za izbrano državo.",
    failed: "Spremembe ni bilo mogoče shraniti. Poskusite znova.",
    changed: "Adresar posodobljen.",
    deleteConfirm: "Želite izbrisati ta naslov?",
    deleteConfirmYes: "Izbriši naslov",
    backToAccount: "← Nazaj na račun",
  },
  /** Name and password changes from /racun/podatki (QA T3-A1). */
  profile: {
    title: "Ime in geslo",
    firstName: "Ime",
    lastName: "Priimek",
    saveName: "Shrani ime",
    nameSaved: "Ime je shranjeno.",
    invalidName: "Vnesite ime in priimek (do 60 znakov vsak).",
    passwordTitle: "Sprememba gesla",
    passwordHint: "Po spremembi gesla boste odjavljeni na vseh napravah, tudi na tej, in se prijavite z novim geslom.",
    currentPassword: "Trenutno geslo",
    newPassword: "Novo geslo (vsaj 8 znakov)",
    savePassword: "Spremeni geslo",
    wrongPassword: "Trenutno geslo ni pravilno.",
    weakPassword: "Novo geslo mora imeti od 8 do 72 znakov.",
    samePassword: "Novo geslo mora biti drugačno od trenutnega.",
    rateLimited: "Preveč poskusov. Počakajte nekaj minut in poskusite znova.",
    failed: "Spremembe ni bilo mogoče shraniti. Poskusite znova.",
  },
} as const;
