/** Account dashboard copy. */
export const account = {
  greeting: "Živjo",
  rows: {
    orders: "Moja naročila",
    details: "Moji podatki",
    support: "Kontaktirajte podporo",
    logout: "Odjava",
  },
  orders: {
    title: "Moja naročila",
    empty: "Še nimate naročil — vaše prvo vas čaka v trgovini.",
    showMore: "Pokaži več",
    showLess: "Pokaži manj",
    shippedWith: "Odposlano z",
    detailLink: "Podrobnosti naročila",
    reviewCta: "Ocenite izdelek",
    reviewed: "Ocenjeno ✓",
  },
  statuses: {
    PENDING: "V obdelavi",
    PAID: "Plačano",
    PROCESSING: "V pripravi",
    SHIPPED: "Odposlano",
    DELIVERED: "Dostavljeno",
    CANCELLED: "Preklicano",
    REFUNDED: "Povrnjeno",
  } as const,
  detail: {
    back: "← Nazaj na naročila",
    lines: "Postavke",
    totals: "Zneski",
    subtotal: "Vmesna vsota",
    discount: "Popust",
    shipping: "Dostava",
    total: "Skupaj",
    addresses: "Naslovi",
    shippingAddress: "Naslov za dostavo",
    billingAddress: "Naslov za račun",
    payment: "Plačilo",
    paymentMethods: { stripe: "Kartica / Apple Pay / Google Pay", paypal: "PayPal", test: "Testno plačilo" },
    vat: "Vključen DDV",
    invoice: "Prenesi račun (PDF)",
    tracking: "Sledenje pošiljke",
    statusLabel: "Status",
  },
  addresses: {
    title: "Moji podatki",
    book: "Adresar",
    add: "Dodaj naslov",
    edit: "Uredi",
    delete: "Izbriši",
    setDefault: "Nastavi kot privzeti",
    default: "Privzeti",
    fullName: "Ime in priimek",
    line1: "Ulica in hišna številka",
    line2: "Dopolnilo (neobvezno)",
    postalCode: "Poštna številka",
    city: "Kraj",
    country: "Država",
    phone: "Telefon",
    label: "Oznaka (npr. Dom, Služba)",
    save: "Shrani naslov",
    saved: "Naslov shranjen.",
    empty: "Adresar je prazen.",
    marketing: "Prejemanje e-novic",
    marketingSaved: "Nastavitve shranjene.",
    profileTitle: "Profil",
    cancel: "Prekliči",
    invalid: "Preverite naslov in obliko poštne številke za izbrano državo.",
    failed: "Spremembe ni bilo mogoče shraniti. Poskusite znova.",
    changed: "Adresar posodobljen.",
  },
} as const;
