/** Admin surface copy (Phase 7). Keyed per screen; every admin string lives here. */
export const admin = {
  title: "Nadzorna plošča",
  shell: {
    brand: "Nasmeh.si · skrbništvo",
    navLabel: "Skrbniška navigacija",
    signedInAs: "Prijavljeni kot",
    roleLabel: "Vloga",
    logout: "Odjava",
    toStore: "Na trgovino",
    forbidden: "Za to stran nimate dovoljenja. Prikazana je nadzorna plošča.",
    nav: {
      dashboard: "Nadzorna plošča",
      orders: "Naročila",
      customers: "Stranke",
      tickets: "Podpora",
      products: "Izdelki",
      collections: "Kolekcije",
      bundles: "Paketi",
      coupons: "Kuponi",
      reviews: "Ocene",
      content: "Vsebina",
      settings: "Nastavitve",
      team: "Ekipa",
      account: "Moj račun",
    },
  },
  roles: {
    CUSTOMER: "Stranka",
    OWNER: "Lastnik",
    MANAGER: "Upravitelj",
    SUPPORT: "Podpora",
    FULFILLMENT: "Odprema",
  },
  common: {
    save: "Shrani",
    cancel: "Prekliči",
    done: "Shranjeno.",
    error: "Ni uspelo. Poskusite znova.",
    confirm: "Potrdi",
    back: "Nazaj",
    none: "—",
    yes: "Da",
    no: "Ne",
  },
  stub: {
    title: "V pripravi",
    body: "Ta zaslon prispe v koraku {step} faze 7. Dostop je že omejen z dovoljenji.",
  },
  dashboard: {
    title: "Nadzorna plošča",
    rangeLabel: "Obdobje",
    presets: { "7d": "Zadnjih 7 dni", "30d": "Zadnjih 30 dni", "90d": "Zadnjih 90 dni", custom: "Po meri" },
    from: "Od",
    to: "Do",
    apply: "Prikaži",
    kpis: {
      revenue: "Prihodki (z DDV)",
      orders: "Plačana naročila",
      aov: "Povprečno naročilo",
      itemsPerOrder: "Kosov na naročilo",
      refunded: "Vrnjeno",
      sessions: "Seje",
      conversion: "Konverzija",
      unavailable: "n/a do analitike (faza 8)",
    },
    charts: {
      revenue: "Prihodki po dnevih",
      revenueWeekly: "Prihodki po tednih",
      orders: "Naročila po dnevih",
      ordersWeekly: "Naročila po tednih",
      byProduct: "Prihodki po izdelkih",
      byStatus: "Naročila po statusu (skupaj)",
      other: "Ostalo",
      empty: "Ni podatkov za izbrano obdobje.",
      tableCaption: "Podatki grafa",
    },
    lists: {
      recentOrders: "Zadnja naročila",
      lowStock: "Nizka zaloga",
      lowStockHint: "Prag: {threshold} kosov",
      pendingReviews: "Ocene v čakalni vrsti",
      expiringCoupons: "Kuponi, ki potečejo v 14 dneh",
      empty: "Nič za prikaz.",
      viewAll: "Prikaži vse",
      columns: {
        number: "Številka",
        email: "E-pošta",
        status: "Status",
        total: "Znesek",
        date: "Datum",
        sku: "SKU",
        product: "Izdelek",
        stock: "Zaloga",
        rating: "Ocena",
        code: "Koda",
        endsAt: "Poteče",
        used: "Uporab",
      },
    },
    statuses: {
      PENDING: "Čaka na plačilo",
      PAID: "Plačano",
      PROCESSING: "V obdelavi",
      SHIPPED: "Odposlano",
      DELIVERED: "Dostavljeno",
      CANCELLED: "Preklicano",
      REFUNDED: "Vrnjeno",
    },
  },
  mfa: {
    title: "Nastavite dvostopenjsko preverjanje",
    intro: "Vsak član ekipe se prijavlja z geslom in kodo iz aplikacije za preverjanje pristnosti (npr. Google Authenticator, 1Password, Aegis). Brez tega skrbništvo ni dostopno.",
    step1: "1. V aplikaciji skenirajte kodo QR ali ročno vnesite ključ.",
    step2: "2. Vnesite 6-mestno kodo, ki jo aplikacija prikaže.",
    secretLabel: "Ročni vnos ključa",
    qrAlt: "Koda QR za aplikacijo za preverjanje pristnosti",
    codeLabel: "Koda iz aplikacije",
    submit: "Potrdi in vklopi",
    invalid: "Koda ni pravilna. Preverite čas na napravi in poskusite znova.",
    rateLimited: "Preveč poskusov. Počakajte nekaj minut.",
    doneTitle: "Dvostopenjsko preverjanje je vklopljeno",
    recoveryTitle: "Rezervne kode",
    recoveryIntro: "Vsaka koda velja enkrat in nadomesti aplikacijo, če izgubite dostop do nje. Shranite jih zdaj — prikazane so samo tokrat.",
    recoveryAck: "Shranil sem kode, nadaljuj",
    genericError: "Nastavitev ni uspela. Osvežite stran in poskusite znova.",
  },
  team: {
    title: "Ekipa",
    intro: "Člani ekipe z vlogami. Lastnik ureja vse; upravitelj katalog, promocije in vsebino; podpora naročila, stranke in ocene; odprema naročila in pošiljke.",
    columns: { name: "Ime", email: "E-pošta", role: "Vloga", mfa: "2FA", sessions: "Seje", actions: "Dejanja" },
    mfaOn: "vklopljeno",
    mfaOff: "čaka na nastavitev",
    sessionsVersion: "različica {version}",
    createTitle: "Dodaj člana",
    nameLabel: "Ime",
    emailLabel: "E-pošta",
    roleLabel: "Vloga",
    create: "Dodaj",
    createdTitle: "Član je dodan",
    createdBody: "Začasno geslo (prikazano samo tokrat): {password}. Ob prvi prijavi bo moral nastaviti dvostopenjsko preverjanje.",
    promotedBody: "Obstoječi račun je dobil vlogo {role}. Ob naslednji prijavi bo moral nastaviti dvostopenjsko preverjanje.",
    changeRole: "Spremeni vlogo",
    revokeSessions: "Odjavi povsod",
    resetMfa: "Ponastavi 2FA",
    demote: "Odstrani iz ekipe",
    selfNote: "Lastnih dovoljenj tu ne morete spreminjati.",
    confirmDemote: "Odstranim člana iz ekipe? Račun ostane, vloga postane Stranka.",
    confirmReset: "Ponastavim dvostopenjsko preverjanje? Član ga bo moral znova nastaviti ob prijavi.",
    invalidEmail: "Vnesite veljaven e-poštni naslov.",
    empty: "Ekipa je še prazna.",
  },
  account: {
    title: "Moj račun",
    mfaStatus: "Dvostopenjsko preverjanje",
    mfaSince: "vklopljeno od {date}",
    regenerateTitle: "Nove rezervne kode",
    regenerateIntro: "Stare rezervne kode prenehajo veljati. Vnesite trenutno kodo iz aplikacije.",
    regenerate: "Ustvari nove kode",
    signOutEverywhere: "Odjavi povsod",
    signOutEverywhereHint: "Razveljavi vse vaše seje, tudi to; prijavite se znova.",
    sessionNote: "Skrbniške seje potečejo 12 ur po prijavi.",
  },
} as const;
