/** Admin surface copy (Phase 7). Keyed per screen; every admin string lives here. */
export const admin = {
  title: "Nadzorna plošča",
  shell: {
    brand: "Nasmeh.si · skrbništvo",
    navLabel: "Skrbniška navigacija",
    signedInAs: "Prijavljeni kot",
    roleLabel: "Vloga",
    logout: "Odjava",
    toStore: "Na trgovino",
    forbidden: "Za to stran nimate dovoljenja. Prikazana je nadzorna plošča.",
    nav: {
      dashboard: "Nadzorna plošča",
      orders: "Naročila",
      customers: "Stranke",
      tickets: "Podpora",
      products: "Izdelki",
      collections: "Kolekcije",
      bundles: "Paketi",
      coupons: "Kuponi",
      reviews: "Ocene",
      content: "Vsebina",
      settings: "Nastavitve",
      team: "Ekipa",
      account: "Moj račun",
    },
  },
  roles: {
    CUSTOMER: "Stranka",
    OWNER: "Lastnik",
    MANAGER: "Upravitelj",
    SUPPORT: "Podpora",
    FULFILLMENT: "Odprema",
  },
  common: {
    save: "Shrani",
    cancel: "Prekliči",
    done: "Shranjeno.",
    error: "Ni uspelo. Poskusite znova.",
    confirm: "Potrdi",
    back: "Nazaj",
    none: "—",
    yes: "Da",
    no: "Ne",
    all: "Vsi",
    apply: "Filtriraj",
    reset: "Počisti",
    page: "Stran {page} od {pages}",
    prev: "Prejšnja",
    next: "Naslednja",
  },
  stub: {
    title: "V pripravi",
    body: "Ta zaslon prispe v koraku {step} faze 7. Dostop je že omejen z dovoljenji.",
  },
  dashboard: {
    title: "Nadzorna plošča",
    rangeLabel: "Obdobje",
    presets: { "7d": "Zadnjih 7 dni", "30d": "Zadnjih 30 dni", "90d": "Zadnjih 90 dni", custom: "Po meri" },
    from: "Od",
    to: "Do",
    apply: "Prikaži",
    kpis: {
      revenue: "Prihodki (z DDV)",
      orders: "Plačana naročila",
      aov: "Povprečno naročilo",
      itemsPerOrder: "Kosov na naročilo",
      refunded: "Vrnjeno",
      sessions: "Seje",
      conversion: "Konverzija",
      unavailable: "n/a do analitike (faza 8)",
    },
    charts: {
      revenue: "Prihodki po dnevih",
      revenueWeekly: "Prihodki po tednih",
      orders: "Naročila po dnevih",
      ordersWeekly: "Naročila po tednih",
      byProduct: "Prihodki po izdelkih",
      byStatus: "Naročila po statusu (skupaj)",
      other: "Ostalo",
      empty: "Ni podatkov za izbrano obdobje.",
      tableCaption: "Podatki grafa",
    },
    lists: {
      recentOrders: "Zadnja naročila",
      lowStock: "Nizka zaloga",
      lowStockHint: "Prag: {threshold} kosov",
      pendingReviews: "Ocene v čakalni vrsti",
      expiringCoupons: "Kuponi, ki potečejo v 14 dneh",
      empty: "Nič za prikaz.",
      viewAll: "Prikaži vse",
      columns: {
        number: "Številka",
        email: "E-pošta",
        status: "Status",
        total: "Znesek",
        date: "Datum",
        sku: "SKU",
        product: "Izdelek",
        stock: "Zaloga",
        rating: "Ocena",
        code: "Koda",
        endsAt: "Poteče",
        used: "Uporab",
      },
    },
    statuses: {
      PENDING: "Čaka na plačilo",
      PAID: "Plačano",
      PROCESSING: "V obdelavi",
      SHIPPED: "Odposlano",
      DELIVERED: "Dostavljeno",
      CANCELLED: "Preklicano",
      REFUNDED: "Vrnjeno",
    },
  },
  orders: {
    title: "Naročila",
    searchLabel: "Iskanje (številka, e-pošta, ime, sledenje)",
    filters: { status: "Status", from: "Od", to: "Do", provider: "Plačilo", country: "Država (koda)" },
    export: "Izvozi CSV",
    refundQueue: "Naročil, ki čakajo na vračilo denarja: {count}",
    columns: {
      number: "Številka", date: "Datum", customer: "Stranka", status: "Status", items: "Kosov",
      total: "Znesek", refunded: "Vrnjeno", provider: "Plačilo", country: "Država", tracking: "Sledenje",
    },
    empty: "Ni naročil za izbrane filtre.",
    total: "{total} naročil",
    providers: { stripe: "Kartica / denarnica", paypal: "PayPal", test: "Testno" },
    detail: {
      back: "← Vsa naročila",
      customer: "Stranka",
      guest: "Gost (brez računa)",
      accountLink: "Odpri stranko",
      phone: "Telefon",
      lines: "Postavke",
      bundleComponents: "Sestava paketa",
      totals: "Zneski",
      subtotal: "Vmesna vsota",
      discount: "Popust",
      shipping: "Dostava",
      total: "Skupaj",
      vat: "Vključen DDV",
      refunded: "Vrnjeno",
      remaining: "Preostanek za vračilo",
      payment: "Plačilo",
      providerRef: "Referenca ponudnika",
      addresses: "Naslovi",
      shippingAddress: "Naslov za dostavo",
      billingAddress: "Naslov za račun",
      tracking: "Sledenje",
      noTracking: "Pošiljka še ni odposlana.",
      timeline: "Časovnica",
      notes: "Opombe",
      refunds: "Vračila denarja",
      tickets: "Zahtevki podpore",
      noTickets: "Brez zahtevkov.",
      refundRequired: "Plačilo je bilo prejeto, a naročila ni bilo mogoče izpolniti — potrebno je vračilo denarja.",
      invoice: "Račun (PDF)",
      packingSlip: "Dobavnica (PDF)",
      anonymised: "Osebni podatki stranke so bili anonimizirani.",
      shippingMethod: "Način dostave",
      coupon: "Kupon",
    },
    timeline: {
      created: "Naročilo ustvarjeno",
      paid: "Plačilo prejeto",
      payment_failed: "Plačilo ni uspelo",
      payment_cancelled: "Plačilo preklicano",
      payment_received_refund_required: "Plačilo prejeto, potrebno vračilo",
      processing: "V obdelavi",
      shipped: "Odposlano",
      delivered: "Dostavljeno",
      cancelled: "Preklicano",
      refunded: "Vrnjeno v celoti",
      partially_refunded: "Delno vrnjeno",
      mail_sent: "Sporočilo poslano",
      mail_failed: "Sporočila ni bilo mogoče poslati",
    },
    actions: {
      title: "Dejanja",
      processing: "Označi kot v obdelavi",
      ship: "Odpošlji",
      carrier: "Prevoznik",
      chooseCarrier: "Izberite prevoznika",
      trackingNumber: "Številka sledenja",
      shipHint: "Prevoznik in številka sledenja sta obvezna; stranka prejme sporočilo s povezavo za sledenje.",
      deliver: "Označi kot dostavljeno",
      cancel: "Prekliči naročilo",
      cancelHint: "Plačano naročilo se vrne v celoti in izdelki se vrnejo na zalogo.",
      cancelReason: "Razlog preklica",
      confirmCancel: "Prekličem naročilo? Plačani znesek bo vrnjen v celoti.",
      refundTitle: "Vračilo denarja",
      refundQuantity: "Količina",
      refundShipping: "Vrni tudi poštnino ({amount})",
      adjustment: "Prilagoditev v centih (npr. −500 za upoštevanje popusta)",
      reason: "Razlog vračila",
      restock: "Vrni izdelke na zalogo",
      refundSubmit: "Izvedi vračilo",
      refundHint: "Znesek se izračuna iz izbranih količin; delno vračilo ohrani status naročila, polno ga zaključi.",
      refundPreview: "Izračunani znesek: {amount}",
      confirmRefund: "Izvedem vračilo v znesku {amount}?",
      resendConfirmation: "Ponovno pošlji potrditev naročila",
      resendShipped: "Ponovno pošlji obvestilo o odpremi",
      results: {
        processing: "Naročilo je v obdelavi.",
        shipped: "Naročilo je odposlano; obvestilo je poslano.",
        delivered: "Naročilo je označeno kot dostavljeno.",
        cancelled: "Naročilo je preklicano.",
        refunded: "Vračilo je izvedeno.",
        resent: "Sporočilo je bilo poslano.",
        resendQueued: "Sporočilo je v vrsti; dnevno opravilo ga bo ponovno poskusilo poslati.",
        invalid_transition: "Ta prehod v trenutnem statusu ni dovoljen.",
        missing_tracking: "Vnesite veljavno številko sledenja (6–40 znakov).",
        unknown_carrier: "Izberite prevoznika iz nastavitev dostave.",
        not_refundable: "Naročila v tem statusu ni mogoče vrniti.",
        pending: "Prejšnje vračilo še ni zaključeno.",
        invalid_lines: "Preverite količine za vračilo.",
        amount: "Znesek je nič ali presega preostanek.",
        provider: "Ponudnik plačil je zavrnil vračilo.",
        provider_unavailable: "Ponudnik plačil za to naročilo ni na voljo.",
        not_found: "Naročila ni mogoče najti.",
        invalid: "Preverite vnesene podatke.",
      },
    },
    notes: {
      add: "Dodaj opombo",
      body: "Besedilo opombe",
      visible: "Vidno stranki (prikaže se v razdelku Moj račun)",
      internal: "Interno",
      customerVisible: "Vidno stranki",
      empty: "Brez opomb.",
      submit: "Shrani opombo",
    },
    refundColumns: { date: "Datum", amount: "Znesek", vat: "DDV", reason: "Razlog", status: "Status", provider: "Ref.", actor: "Izvedel", restocked: "Zaloga" },
    refundStatuses: { PENDING: "V teku", COMPLETED: "Zaključeno", FAILED: "Neuspešno" },
  },
  packingSlip: {
    title: "Dobavnica",
    order: "Naročilo",
    date: "Datum",
    shipTo: "Dostava na naslov",
    items: "Vsebina pošiljke",
    component: "sestavina",
    method: "Način dostave",
    footer: "Dobavnica ne vsebuje cen. Račun je bil poslan po e-pošti.",
  },
  customers: {
    title: "Stranke",
    searchLabel: "Iskanje (e-pošta, ime)",
    filters: { hasOrders: "Z naročili", marketing: "E-novice" },
    columns: { name: "Ime", email: "E-pošta", type: "Vrsta", orders: "Naročil", ltv: "Vrednost nakupov", marketing: "E-novice", created: "Od" },
    types: { account: "Račun", guest: "Gost" },
    empty: "Ni strank za izbrane filtre.",
    total: "{total} strank",
    detail: {
      back: "← Vse stranke",
      profile: "Profil",
      addresses: "Adresar",
      orders: "Naročila",
      consents: "Soglasja",
      tickets: "Zahtevki podpore",
      notes: "Interne opombe in oznake",
      tags: "Oznake (ločene z vejico)",
      adminNotes: "Interne opombe",
      export: "Izvozi podatke (JSON)",
      anonymise: "Anonimiziraj stranko",
      anonymiseHint: "Odstrani osebne podatke iz računa, adresarja, naročil, zahtevkov in prijav na obvestila; zneski naročil ostanejo. Postopka ni mogoče razveljaviti.",
      confirmAnonymise: "Anonimiziram to stranko? Postopka ni mogoče razveljaviti.",
      anonymised: "Anonimizirano {date}",
      guestNote: "Gost brez računa — podatki izhajajo iz naročil s tem e-poštnim naslovom.",
      marketingOptIn: "Soglasje za e-novice",
      ltv: "Skupna vrednost nakupov",
      orderCount: "Število naročil",
      registered: "Registriran",
      verified: "E-pošta potrjena",
      role: "Vloga",
      noAddresses: "Brez naslovov.",
      noOrders: "Brez naročil.",
      noConsents: "Brez zabeleženih soglasij.",
      noTickets: "Brez zahtevkov.",
      consentColumns: { date: "Datum", kind: "Vrsta", choices: "Izbira" },
    },
  },
  tickets: {
    title: "Podpora",
    filters: { status: "Status", topic: "Tema" },
    columns: { reference: "Referenca", date: "Datum", topic: "Tema", reason: "Razlog", name: "Ime", email: "E-pošta", order: "Naročilo", status: "Status", assignee: "Dodeljen" },
    empty: "Ni zahtevkov za izbrane filtre.",
    total: "{total} zahtevkov",
    statuses: { OPEN: "Odprt", IN_PROGRESS: "V obdelavi", CLOSED: "Zaključen" },
    detail: {
      back: "← Vsi zahtevki",
      message: "Sporočilo",
      details: "Strukturirani podatki",
      attachments: "Priloge",
      attachment: "Priloga {n}",
      order: "Naročilo",
      proof: "Dokazilo o naročilu",
      proofAccount: "prijavljen račun",
      proofEmailNumber: "e-pošta in številka naročila",
      reporter: "Prijavitelj",
      customer: "Stranka",
      status: "Status",
      assignee: "Dodeljen",
      unassigned: "Nikomur",
      internalNote: "Interna opomba",
      privacy: "Zasebnost sprejeta",
      deliveries: "Dostava e-pošte",
      deliverySent: "poslano",
      deliveryPending: "v vrsti",
    },
  },
  mfa: {
    title: "Nastavite dvostopenjsko preverjanje",
    intro: "Vsak član ekipe se prijavlja z geslom in kodo iz aplikacije za preverjanje pristnosti (npr. Google Authenticator, 1Password, Aegis). Brez tega skrbništvo ni dostopno.",
    step1: "1. V aplikaciji skenirajte kodo QR ali ročno vnesite ključ.",
    step2: "2. Vnesite 6-mestno kodo, ki jo aplikacija prikaže.",
    secretLabel: "Ročni vnos ključa",
    qrAlt: "Koda QR za aplikacijo za preverjanje pristnosti",
    codeLabel: "Koda iz aplikacije",
    submit: "Potrdi in vklopi",
    invalid: "Koda ni pravilna. Preverite čas na napravi in poskusite znova.",
    rateLimited: "Preveč poskusov. Počakajte nekaj minut.",
    doneTitle: "Dvostopenjsko preverjanje je vklopljeno",
    recoveryTitle: "Rezervne kode",
    recoveryIntro: "Vsaka koda velja enkrat in nadomesti aplikacijo, če izgubite dostop do nje. Shranite jih zdaj — prikazane so samo tokrat.",
    recoveryAck: "Shranil sem kode, nadaljuj",
    genericError: "Nastavitev ni uspela. Osvežite stran in poskusite znova.",
  },
  team: {
    title: "Ekipa",
    intro: "Člani ekipe z vlogami. Lastnik ureja vse; upravitelj katalog, promocije in vsebino; podpora naročila, stranke in ocene; odprema naročila in pošiljke.",
    columns: { name: "Ime", email: "E-pošta", role: "Vloga", mfa: "2FA", sessions: "Seje", actions: "Dejanja" },
    mfaOn: "vklopljeno",
    mfaOff: "čaka na nastavitev",
    sessionsVersion: "različica {version}",
    createTitle: "Dodaj člana",
    nameLabel: "Ime",
    emailLabel: "E-pošta",
    roleLabel: "Vloga",
    create: "Dodaj",
    createdTitle: "Član je dodan",
    createdBody: "Začasno geslo (prikazano samo tokrat): {password}. Ob prvi prijavi bo moral nastaviti dvostopenjsko preverjanje.",
    promotedBody: "Obstoječi račun je dobil vlogo {role}. Ob naslednji prijavi bo moral nastaviti dvostopenjsko preverjanje.",
    changeRole: "Spremeni vlogo",
    revokeSessions: "Odjavi povsod",
    resetMfa: "Ponastavi 2FA",
    demote: "Odstrani iz ekipe",
    selfNote: "Lastnih dovoljenj tu ne morete spreminjati.",
    confirmDemote: "Odstranim člana iz ekipe? Račun ostane, vloga postane Stranka.",
    confirmReset: "Ponastavim dvostopenjsko preverjanje? Član ga bo moral znova nastaviti ob prijavi.",
    invalidEmail: "Vnesite veljaven e-poštni naslov.",
    empty: "Ekipa je še prazna.",
  },
  account: {
    title: "Moj račun",
    mfaStatus: "Dvostopenjsko preverjanje",
    mfaSince: "vklopljeno od {date}",
    regenerateTitle: "Nove rezervne kode",
    regenerateIntro: "Stare rezervne kode prenehajo veljati. Vnesite trenutno kodo iz aplikacije.",
    regenerate: "Ustvari nove kode",
    signOutEverywhere: "Odjavi povsod",
    signOutEverywhereHint: "Razveljavi vse vaše seje, tudi to; prijavite se znova.",
    sessionNote: "Skrbniške seje potečejo 12 ur po prijavi.",
  },
} as const;
