/** Admin surface copy (Phase 7). Keyed per screen; every admin string lives here. */
export const admin = {
  title: "Nadzorna plošča",
  shell: {
    brand: "Nasmeh.si · skrbništvo",
    navLabel: "Skrbniška navigacija",
    signedInAs: "Prijavljeni kot",
    roleLabel: "Vloga",
    logout: "Odjava",
    toStore: "Na trgovino",
    forbidden: "Za to stran nimate dovoljenja. Prikazana je nadzorna plošča.",
    nav: {
      dashboard: "Nadzorna plošča",
      orders: "Naročila",
      customers: "Stranke",
      tickets: "Podpora",
      products: "Izdelki",
      collections: "Kolekcije",
      bundles: "Paketi",
      coupons: "Kuponi",
      reviews: "Ocene",
      content: "Vsebina",
      pages: "Strani",
      menus: "Navigacija",
      media: "Mediji",
      email: "E-pošta",
      settings: "Nastavitve",
      team: "Ekipa",
      account: "Moj račun",
    },
  },
  roles: {
    CUSTOMER: "Stranka",
    OWNER: "Lastnik",
    MANAGER: "Upravitelj",
    SUPPORT: "Podpora",
    FULFILLMENT: "Odprema",
  },
  common: {
    save: "Shrani",
    cancel: "Prekliči",
    done: "Shranjeno.",
    error: "Ni uspelo. Poskusite znova.",
    confirm: "Potrdi",
    back: "Nazaj",
    none: "—",
    yes: "Da",
    no: "Ne",
    all: "Vsi",
    apply: "Filtriraj",
    reset: "Počisti",
    page: "Stran {page} od {pages}",
    truncated: "Prikazanih je največ {n} vnosov; zožite iskanje ali filtre.",
    prev: "Prejšnja",
    next: "Naslednja",
  },
  dashboard: {
    title: "Nadzorna plošča",
    rangeLabel: "Obdobje",
    presets: { "7d": "Zadnjih 7 dni", "30d": "Zadnjih 30 dni", "90d": "Zadnjih 90 dni", custom: "Po meri" },
    from: "Od",
    to: "Do",
    apply: "Prikaži",
    /** A custom range the page could not use; it says so instead of silently showing 30 days (QA N1). */
    invalidRange: {
      reversed: "Datum »Do« je pred datumom »Od«; prikazanih je zadnjih 30 dni.",
      too_long: "Obdobje je daljše od {max} dni; prikazanih je zadnjih 30 dni.",
      malformed: "Vnesena datuma nista veljavna; prikazanih je zadnjih 30 dni.",
    },
    kpis: {
      revenue: "Prihodki (z DDV)",
      orders: "Plačana naročila",
      aov: "Povprečno naročilo",
      itemsPerOrder: "Kosov na naročilo",
      refunded: "Vrnjeno",
      sessions: "Seje",
      conversion: "Konverzija",
      unavailable: "n/a do analitike (faza 8)",
    },
    charts: {
      revenue: "Prihodki po dnevih",
      revenueWeekly: "Prihodki po tednih",
      orders: "Naročila po dnevih",
      ordersWeekly: "Naročila po tednih",
      byProduct: "Prihodki po izdelkih",
      byStatus: "Naročila po statusu (skupaj)",
      other: "Ostalo",
      empty: "Ni podatkov za izbrano obdobje.",
      tableCaption: "Podatki grafa",
    },
    lists: {
      recentOrders: "Zadnja naročila",
      lowStock: "Nizka zaloga",
      lowStockHint: "Prag: {threshold} kosov",
      pendingReviews: "Ocene v čakalni vrsti",
      expiringCoupons: "Kuponi, ki potečejo v 14 dneh",
      empty: "Nič za prikaz.",
      viewAll: "Prikaži vse",
      columns: {
        number: "Številka",
        email: "E-pošta",
        status: "Status",
        total: "Znesek",
        date: "Datum",
        sku: "SKU",
        product: "Izdelek",
        stock: "Zaloga",
        rating: "Ocena",
        code: "Koda",
        endsAt: "Poteče",
        used: "Uporab",
      },
    },
    statuses: {
      PENDING: "Čaka na plačilo",
      PAID: "Plačano",
      PROCESSING: "V obdelavi",
      SHIPPED: "Odposlano",
      DELIVERED: "Dostavljeno",
      CANCELLED: "Preklicano",
      REFUNDED: "Vrnjeno",
    },
  },
  orders: {
    title: "Naročila",
    searchLabel: "Iskanje (številka, e-pošta, ime, sledenje)",
    filters: { status: "Status", from: "Od", to: "Do", provider: "Plačilo", country: "Država (koda)" },
    export: "Izvozi CSV",
    refundQueue: "Naročil, ki čakajo na vračilo denarja: {count}",
    columns: {
      number: "Številka", date: "Datum", customer: "Stranka", status: "Status", items: "Kosov",
      total: "Znesek", refunded: "Vrnjeno", provider: "Plačilo", country: "Država", tracking: "Sledenje",
    },
    empty: "Ni naročil za izbrane filtre.",
    total: "{total} naročil",
    providers: { stripe: "Kartica / denarnica", paypal: "PayPal", test: "Testno" },
    detail: {
      back: "← Vsa naročila",
      customer: "Stranka",
      guest: "Gost (brez računa)",
      accountLink: "Odpri stranko",
      phone: "Telefon",
      lines: "Postavke",
      bundleComponents: "Sestava paketa",
      totals: "Zneski",
      subtotal: "Vmesna vsota",
      discount: "Popust",
      shipping: "Dostava",
      total: "Skupaj",
      vat: "Vključen DDV",
      refunded: "Vrnjeno",
      remaining: "Preostanek za vračilo",
      payment: "Plačilo",
      providerRef: "Referenca ponudnika",
      addresses: "Naslovi",
      shippingAddress: "Naslov za dostavo",
      billingAddress: "Naslov za račun",
      tracking: "Sledenje",
      noTracking: "Pošiljka še ni odposlana.",
      timeline: "Časovnica",
      notes: "Opombe",
      refunds: "Vračila denarja",
      tickets: "Zahtevki podpore",
      noTickets: "Brez zahtevkov.",
      unlinkedTickets: "Nepovezani odstopi s to številko naročila",
      unlinkedTicketsHint: "Potrošnik je v odstopu navedel to številko naročila, a naročila ni bilo mogoče samodejno potrditi (npr. druga e-pošta). Odstop učinkuje z obvestilom; naročilo preverite ročno.",
      unlinkedTag: "ni povezan",
      unlinkedOtherTickets: "Drugi nepovezani zahtevki s to številko naročila",
      unlinkedOtherTicketsHint: "Prijavitelj (npr. prijave neželenega učinka) je navedel to številko naročila, a je ni bilo mogoče samodejno potrditi. Zahtevek preverite ročno.",
      refundRequired: "Plačilo je bilo prejeto, a naročila ni bilo mogoče izpolniti — potrebno je vračilo denarja.",
      /** Why the money is owed; the key is `Order.fulfillmentIssue` (the stock-out carries the variant). */
      refundRequiredReasons: {
        stockout: "Vzrok: ob prejemu plačila izdelka ni bilo več na zalogi ({sku}). Zaloga ni bila odšteta.",
        payment_received_after_cancellation: "Vzrok: plačilo je prispelo po preklicu naročila.",
        payment_received_after_anonymisation: "Vzrok: plačilo je prispelo po anonimizaciji kupca; naročila ni mogoče izpolniti.",
        stockoutUnknown: "Vzrok: ob prejemu plačila izdelka ni bilo več na zalogi. Zaloga ni bila odšteta.",
        invalid_inventory_snapshot: "Vzrok: zaloge ob prejemu plačila ni bilo mogoče preveriti. Zaloga ni bila odšteta.",
      },
      refundRequiredHint: "Prejeti znesek vrnete z gumbom »Vrni prejeto plačilo« v razdelku Dejanja; po vračilu naročilo ne čaka več na vračilo denarja.",
      /** Shown instead of the hint to a role without `orders:refund` (the button is not rendered for it). */
      refundRequiredHintNoPermission: "Prejeti znesek vrne član ekipe s pravico do vračil (lastnik ali podpora); do takrat naročilo čaka na vračilo denarja.",
      refundRequiredTag: "čaka na vračilo",
      invoice: "Račun (PDF)",
      packingSlip: "Dobavnica (PDF)",
      anonymised: "Osebni podatki stranke so bili anonimizirani.",
      shippingMethod: "Način dostave",
      coupon: "Kupon",
    },
    timeline: {
      created: "Naročilo ustvarjeno",
      paid: "Plačilo prejeto",
      payment_failed: "Plačilo ni uspelo",
      payment_cancelled: "Plačilo preklicano",
      payment_received_refund_required: "Plačilo prejeto, potrebno vračilo",
      processing: "V obdelavi",
      shipped: "Odposlano",
      delivered: "Dostavljeno",
      cancelled: "Preklicano",
      refunded: "Vrnjeno v celoti",
      partially_refunded: "Delno vrnjeno",
      restock_skipped: "Vrnitev na zalogo preskočena (različica je bila izbrisana)",
      refund_interrupted: "Vračilo prekinjeno pred potrditvijo ponudnika – preverite pri ponudniku plačil",
      mail_sent: "Sporočilo poslano",
      mail_failed: "Sporočila ni bilo mogoče poslati",
      note_added: "Opomba dodana",
      confirmation_resent: "Potrditev naročila znova poslana",
      shipped_resent: "Obvestilo o odpremi znova poslano",
      confirmation_requeued: "Potrditev naročila v vrsti za ponovno pošiljanje",
      shipped_requeued: "Obvestilo o odpremi v vrsti za ponovno pošiljanje",
      anonymised: "Osebni podatki anonimizirani",
      /** Readable renderings of the raw `detail` strings the transitions record (QA N3). */
      details: {
        provider: "ponudnik plačil: {provider}",
        amount: "znesek: {amount}",
        actor: "izvedel: {actor}",
        carrier: "prevoznik: {carrier}",
        reason: "razlog: {reason}",
        variants: "izbrisanih različic: {count}",
        stockout: "izdelka ni bilo več na zalogi: {sku}",
        stockoutUnknown: "izdelka ni bilo več na zalogi",
        mailKinds: { processing: "v obdelavi", delivered: "dostavljeno", cancelled: "preklicano", refunded: "vračilo denarja", confirmation: "potrditev naročila", shipped: "odprema" },
      },
    },
    actions: {
      title: "Dejanja",
      processing: "Označi kot v obdelavi",
      ship: "Odpošlji",
      carrier: "Prevoznik",
      chooseCarrier: "Izberite prevoznika",
      trackingNumber: "Številka sledenja",
      shipHint: "Prevoznik in številka sledenja sta obvezna; stranka prejme sporočilo s povezavo za sledenje.",
      deliver: "Označi kot dostavljeno",
      cancel: "Prekliči naročilo",
      cancelHint: "Plačano naročilo se vrne v celoti in izdelki se vrnejo na zalogo.",
      cancelReason: "Razlog preklica",
      confirmCancel: "Prekličem naročilo? Plačani znesek bo vrnjen v celoti.",
      refundTitle: "Vračilo denarja",
      refundQuantity: "Količina",
      refundShipping: "Vrni tudi poštnino ({amount})",
      adjustment: "Prilagoditev v evrih (npr. −5,00 za upoštevanje popusta)",
      adjustmentInvalid: "Prilagoditev vnesite v evrih, npr. −5,00.",
      reason: "Razlog vračila",
      settle: "Vrni prejeto plačilo",
      settleHint: "Naročila ni bilo mogoče izpolniti: prejeti znesek {amount} se v celoti vrne prek ponudnika plačil, zaloga se ne spreminja, stranka prejme obvestilo o vračilu.",
      confirmSettle: "Vrnem prejeto plačilo v znesku {amount}?",
      restock: "Vrni izdelke na zalogo",
      refundSubmit: "Izvedi vračilo",
      refundHint: "Znesek se izračuna iz izbranih količin; delno vračilo ohrani status naročila, polno ga zaključi.",
      refundPreview: "Izračunani znesek: {amount}",
      confirmRefund: "Izvedem vračilo v znesku {amount}?",
      resendConfirmation: "Ponovno pošlji potrditev naročila",
      resendShipped: "Ponovno pošlji obvestilo o odpremi",
      results: {
        processing: "Naročilo je v obdelavi.",
        shipped: "Naročilo je odposlano; obvestilo je poslano.",
        delivered: "Naročilo je označeno kot dostavljeno.",
        cancelled: "Naročilo je preklicano.",
        refunded: "Vračilo je izvedeno.",
        settled: "Prejeto plačilo je vrnjeno; naročilo ne čaka več na vračilo denarja.",
        resent: "Sporočilo je bilo poslano.",
        resendQueued: "Sporočilo je v vrsti; dnevno opravilo ga bo ponovno poskusilo poslati.",
        invalid_transition: "Ta prehod v trenutnem statusu ni dovoljen.",
        missing_tracking: "Vnesite veljavno številko sledenja (6–40 znakov).",
        unknown_carrier: "Izberite prevoznika iz nastavitev dostave.",
        not_refundable: "Naročila v tem statusu ni mogoče vrniti.",
        pending: "Prejšnje vračilo še ni zaključeno.",
        deferred: "Ponudnik plačil je vračilo sprejel, naročila pa še ni bilo mogoče posodobiti. Stanje se uskladi samodejno z naslednjim dejanjem na naročilu ali z dnevnim opravilom.",
        invalid_lines: "Preverite količine za vračilo.",
        amount: "Znesek je nič ali presega preostanek.",
        provider: "Ponudnik plačil je zavrnil vračilo.",
        provider_unavailable: "Ponudnik plačil za to naročilo ni na voljo.",
        not_found: "Naročila ni mogoče najti.",
        invalid: "Preverite vnesene podatke.",
      },
    },
    notes: {
      add: "Dodaj opombo",
      body: "Besedilo opombe",
      visible: "Vidno stranki (prikaže se v razdelku Moj račun)",
      internal: "Interno",
      customerVisible: "Vidno stranki",
      empty: "Brez opomb.",
      submit: "Shrani opombo",
    },
    refundColumns: { date: "Datum", amount: "Znesek", vat: "DDV", reason: "Razlog", status: "Status", provider: "Ref.", actor: "Izvedel", restocked: "Zaloga" },
    refundStatuses: { PENDING: "V teku", COMPLETED: "Zaključeno", FAILED: "Neuspešno" },
  },
  packingSlip: {
    title: "Dobavnica",
    order: "Naročilo",
    date: "Datum",
    shipTo: "Dostava na naslov",
    items: "Vsebina pošiljke",
    component: "sestavina",
    method: "Način dostave",
    footer: "Dobavnica ne vsebuje cen. Račun je bil poslan po e-pošti.",
  },
  customers: {
    title: "Stranke",
    searchLabel: "Iskanje (e-pošta, ime)",
    filters: { hasOrders: "Z naročili", marketing: "E-novice" },
    columns: { name: "Ime", email: "E-pošta", type: "Vrsta", orders: "Naročil", ltv: "Vrednost nakupov", marketing: "E-novice", created: "Od" },
    types: { account: "Račun", guest: "Gost" },
    empty: "Ni strank za izbrane filtre.",
    total: "{total} strank",
    findByEmail: { label: "Odpri osebo po e-poštnem naslovu (tudi brez naročil)", submit: "Odpri" },
    anonymisedNotice: "Oseba je anonimizirana. Njena stran ni več dosegljiva, ker e-poštni naslov ni več shranjen.",
    detail: {
      back: "← Vse stranke",
      profile: "Profil",
      addresses: "Adresar",
      orders: "Naročila",
      consents: "Soglasja",
      tickets: "Zahtevki podpore",
      notes: "Interne opombe in oznake",
      tags: "Oznake (ločene z vejico)",
      adminNotes: "Interne opombe",
      export: "Izvozi podatke (JSON)",
      anonymise: "Anonimiziraj stranko",
      anonymiseHint: "Odstrani osebne podatke iz računa, adresarja, naročil, zahtevkov, prijav na e-novice in obvestila o zalogi ter nedokončanih nakupov. Ostanejo zneski naročil, podatki izdanih računov in evidenca soglasij. Postopka ni mogoče razveljaviti.",
      confirmAnonymise: "Anonimiziram to stranko? Postopka ni mogoče razveljaviti.",
      /** Why an erasure was refused; the key is the reason the Server Action returns. */
      anonymiseRefused: {
        account: "Ta e-poštni naslov ima uporabniški račun. Anonimizirajte ga na strani računa, ki zajame tudi naročila brez prijave.",
        open_order: "Oseba ima odprto naročilo (neplačano ali plačano in še neodposlano). Najprej ga zaključite ali prekličite, nato anonimizirajte.",
        staff: "Ta račun pripada članu ekipe. Najprej ga v Ekipi odstranite iz ekipe, nato anonimizirajte.",
        not_found: "Osebe ni mogoče najti; stran osvežite.",
      },
      anonymised: "Anonimizirano {date}",
      guestNote: "Gost brez računa — podatki izhajajo iz naročil, zahtevkov, prijav na e-novice in obvestila o zalogi ter nedokončanih nakupov s tem e-poštnim naslovom.",
      otherRecords: "Druge evidence",
      newsletter: "Prijava na e-novice",
      backInStock: "Obvestila o zalogi",
      abandonedCheckouts: "Nedokončani nakupi",
      abandonedCheckoutsSummary: "{n}, nazadnje {date}",
      subscriberStatuses: { PENDING: "čaka na potrditev", CONFIRMED: "potrjena", UNSUBSCRIBED: "odjavljena" },
      marketingOptIn: "Soglasje za e-novice",
      ltv: "Skupna vrednost nakupov",
      orderCount: "Število naročil",
      registered: "Registriran",
      verified: "E-pošta potrjena",
      role: "Vloga",
      noAddresses: "Brez naslovov.",
      noOrders: "Brez naročil.",
      noConsents: "Brez zabeleženih soglasij.",
      noTickets: "Brez zahtevkov.",
      consentColumns: { date: "Datum", kind: "Vrsta", choices: "Izbira" },
      /** Readable consent history (QA cosmetics): the kind, then the stored choices by label. */
      consentKinds: {
        cookie: "Piškotki",
        "marketing-checkout": "E-novice ob nakupu",
        "marketing-register": "E-novice ob registraciji",
        "marketing-activation": "E-novice ob potrditvi računa",
        "marketing-preference": "E-novice v računu",
        "marketing-email": "E-novice (obrazec)",
        "back-in-stock": "Obvestilo o zalogi",
      },
      consentVersion: "različica {version}",
      /** A cookie row's keys are the CMP categories: `marketing` there is the marketing-cookie category, not the newsletter. */
      consentCookieCategories: { necessary: "nujni", analytics: "analitični", marketing: "trženjski" },
      consentChoices: {
        marketing: "e-novice",
        necessary: "nujni",
        analytics: "analitični",
        previous: "prej",
        action: "dejanje",
        orderNumber: "naročilo",
        source: "vir",
        doubleOptIn: "dvojna potrditev",
        withdrawn: "preklic",
        unsubscribed: "odjava",
        previousStatus: "prejšnje stanje",
        subscriberStatus: "stanje prijave",
        productSlug: "izdelek",
        pendingVerification: "čaka na potrditev e-pošte",
        verified: "e-pošta potrjena",
        requested: "zahtevano",
        withdrawnAfterIssue: "preklicano po izdaji",
        reason: "razlog",
      },
      /**
       * The stored codes in words (QA round 2): what the writers put in `action`, `source`,
       * `reason` and `subscriberStatus`. Subscriber statuses (PENDING…) read through
       * `subscriberStatuses`; an unknown future code is shown as stored.
       */
      consentValues: {
        "not-given": "soglasje ni podano",
        "pending-confirmation": "čaka na potrditev",
        "already-confirmed": "že potrjena",
        none: "brez prijave",
        anonymised: "anonimizacija",
        footer: "noga strani",
        "welcome-popup": "pozdravno okno",
        checkout: "zaključek nakupa",
        account: "nastavitve računa",
        "account-preference": "nastavitve računa",
        register: "registracija",
        "post-purchase": "registracija po nakupu",
        "post-purchase-resend": "registracija po nakupu (ponovno poslana povezava)",
        "newsletter-unsubscribe": "odjava od e-novic",
        "unsubscribe-link": "povezava za odjavo",
        "back-in-stock": "obvestilo o zalogi",
      },
    },
  },
  tickets: {
    title: "Podpora",
    filters: { status: "Status", topic: "Tema" },
    columns: { reference: "Referenca", date: "Datum", topic: "Tema", reason: "Razlog", name: "Ime", email: "E-pošta", order: "Naročilo", status: "Status", assignee: "Dodeljen" },
    empty: "Ni zahtevkov za izbrane filtre.",
    total: "{total} zahtevkov",
    statuses: { OPEN: "Odprt", IN_PROGRESS: "V obdelavi", CLOSED: "Zaključen" },
    detail: {
      back: "← Vsi zahtevki",
      message: "Sporočilo",
      details: "Strukturirani podatki",
      attachments: "Priloge",
      attachment: "Priloga {n}",
      order: "Naročilo",
      proof: "Dokazilo o naročilu",
      proofAccount: "prijavljen račun",
      proofEmailNumber: "e-pošta in številka naročila",
      reporter: "Prijavitelj",
      customer: "Stranka",
      status: "Status",
      assignee: "Dodeljen",
      unassigned: "Nikomur",
      internalNote: "Interna opomba",
      privacy: "Zasebnost sprejeta",
      deliveries: "Dostava e-pošte",
      deliverySent: "poslano",
      deliveryPending: "v vrsti",
      deliveryKinds: { STAFF: "Ekipa", CUSTOMER: "Stranka" },
    },
  },
  catalog: {
    products: {
      title: "Izdelki",
      searchLabel: "Iskanje (naziv, slug, SKU)",
      status: "Status",
      newTitle: "Nov izdelek",
      newTitleLabel: "Naziv",
      newSlugLabel: "Slug (URL)",
      newSkuLabel: "SKU prve variante",
      newPriceLabel: "Cena prve variante (centi, z DDV)",
      /** A refused create names the field and its rule at the field itself (QA T6-11, v-a). */
      newErrors: {
        title: "Vpišite naziv izdelka (do 200 znakov).",
        slug: "Slug sme vsebovati le črke brez šumnikov, številke in enojne vezaje med njimi (2–80 znakov), npr. »belilni-trakci«; velike črke se shranijo kot male.",
        sku: "SKU sme vsebovati le črke brez šumnikov, številke in vezaje (2–40 znakov) in se mora začeti s črko ali številko.",
        priceCents: "Cena je celo število centov od 0 do 10000000, npr. 2990 za 29,90 €.",
      },
      create: "Ustvari osnutek",
      created: "Izdelek je ustvarjen kot osnutek.",
      columns: { title: "Naziv", slug: "Slug", status: "Status", price: "Cena", stock: "Zaloga", badges: "Značke", updated: "Spremenjen", subscribers: "Obvestila" },
      empty: "Ni izdelkov za izbrane filtre.",
      statuses: { DRAFT: "Osnutek", ACTIVE: "Aktiven", ARCHIVED: "Arhiviran" },
      bundleTag: "paket",
      lowStockTitle: "Prag nizke zaloge",
      lowStockLabel: "Opozori, ko je zaloga enaka ali manjša od",
      lowStockSave: "Shrani prag",
      lowStockHint: "Celo število od 0 do 1000 kosov; velja za seznam izdelkov in nadzorno ploščo.",
      stockOut: "razprodano",
      stockLow: "nizka zaloga",
    },
    editor: {
      back: "← Vsi izdelki",
      view: "Poglej na trgovini",
      sections: {
        basics: "Osnovni podatki",
        merchandising: "Kartica in trgovanje",
        content: "Vsebina strani izdelka",
        variants: "Variante",
        media: "Mediji",
        history: "Zgodovina cen (Omnibus)",
        restock: "Obvestila o zalogi",
        collections: "Kolekcije",
      },
      fields: {
        title: "Naziv",
        slug: "Slug (URL)",
        status: "Status",
        description: "Opis (HTML dovoljen)",
        seoTitle: "SEO naslov",
        seoDescription: "SEO opis",
        visibleInCatalog: "Prikaz v trgovini",
        visibleInSearch: "Prikaz v iskanju",
        hiddenDeal: "Skriti akcijski SKU (skrit povsod, stran vrne 404)",
        /** What the flag does since the M7 fix (QA v-a): not "only a label". */
        hiddenDealHint: "Izdelek izgine iz trgovine, iskanja, zemljevida strani, menijev in domače strani, njegova stran vrne 404 in ga ni mogoče dodati v košarico. Povezave nanj v menijih, na domači strani in v oglasni vrstici trgovina skrije; povezave v besedilih strani, opisih izdelkov in e-poštnih predlogah preverite sami.",
        klarnaEligible: "Ponudi Klarna obroke (ko so vklopljeni)",
        soldOutBehavior: "Ob razprodaji",
        soldOut: { NOTIFY: "Prikaži »Obvestite me«", HIDE: "Skrij iz seznamov (stran ostane, noindex)" },
      },
      badges: {
        title: "Značke (do 4)",
        label: "Napis",
        style: "Slog",
        add: "Dodaj značko",
        remove: "Odstrani",
        styles: { outline: "Obroba", solid: "Polna", grey: "Siva", warning: "Opozorilo", promo: "Promocija" },
      },
      merchandising: {
        uspChips: "USP oznake (do 3)",
        intro: "Uvod",
        bullets: "Kljukice (do 6)",
        unitPriceQuantity: "Enotna cena — količina",
        unitPriceUnit: "Enotna cena — enota (npr. »na uporabo«)",
        unitPriceHint: "Pustite prazno, če enotne cene ni.",
        crossSell: "Dopolnilni izdelki (do 6)",
        extraJson: "Dodatna polja (JSON objekt, metapolja)",
        add: "Dodaj",
        remove: "Odstrani",
      },
      content: {
        accordions: { howItWorks: "Kako deluje (HTML)", inci: "Sestavine INCI (HTML)", guarantee: "Jamstvo (HTML)", tested: "Opombe k navedbam (HTML)" },
        testedHint: "Na izdelku se prikaže kot »*Opombe k navedbam«. Pojasnite vsako navedbo, označeno z * ali ^ (npr. da se rezultati razlikujejo od osebe do osebe). Številke in rezultate raziskav navedite le, če so dokazila v evidenci.",
        faq: "Pogosta vprašanja (do 12)",
        faqQ: "Vprašanje",
        faqA: "Odgovor",
        education: "Izobraževalni odseki (do 6)",
        educationHeading: "Naslov",
        educationBody: "Besedilo",
      },
      save: "Shrani izdelek",
      saved: "Izdelek je shranjen.",
      invalid: "Preverite vnesene podatke.",
      /** A validation failure names the field (QA T6-11); keys not in `fields`/`fieldNames` fall back to the generic text. */
      invalidField: "Preverite polje »{field}«.",
      fieldNames: { badges: "Značke", faq: "Pogosta vprašanja", education: "Izobraževalni odseki", uspChips: "USP oznake", intro: "Uvod", bullets: "Kljukice", unitPrice: "Enotna cena", crossSell: "Dopolnilni izdelki", extraJson: "Dodatna polja", howItWorks: "Kako deluje", inci: "Sestavine INCI", guarantee: "Jamstvo", tested: "Opombe k navedbam" },
      slugTaken: "Slug je že v uporabi.",
      extraJsonInvalid: "Dodatna polja morajo biti veljaven JSON objekt.",
      variants: {
        title: "Naziv variante",
        sku: "SKU",
        price: "Cena (centi, z DDV)",
        compareAt: "Primerjalna cena (centi)",
        cost: "Nabavna cena (centi)",
        barcode: "Črtna koda",
        weight: "Teža (g)",
        stock: "Zaloga",
        maxCart: "Največ kosov na naročilo",
        allowBackorder: "Dovoli prednaročilo pod zalogo 0",
        backorderNote: "Opomba ob prednaročilu (npr. rok dobave)",
        save: "Shrani varianto",
        add: "Dodaj varianto",
        delete: "Izbriši varianto",
        confirmDelete: "Izbrišem varianto? Postavke starih naročil ostanejo brez povezave.",
        skuTaken: "SKU je že v uporabi.",
        lastVariant: "Zadnje variante izdelka ni mogoče izbrisati.",
        inBundle: "Varianta je sestavina paketa in je ni mogoče izbrisati.",
        bundlePrice: "Ceno paketa uredite v Paketi; tam se posodobita tako cena paketa kot cena variante, da prikazani prihranek ostane resničen.",
        priceHint: "Spremembe cen gredo skozi zgodovino cen (Omnibus), spremembe zaloge skozi pomočnik za zalogo (obvestila »Obvestite me«). Primerjalna cena le vklopi prikaz znižanja: v trgovini je prečrtana najnižja cena iz zgodovine cen v 30 dneh pred znižanjem; če take cene ni ali ni višja od trenutne, je prikazana samo trenutna cena. Znižanje se začne z vklopom primerjalne cene: vnesite jo skupaj z novo ceno ali najpozneje v 24 urah po spremembi cene. Če jo vklopite pozneje ali jo izklopite in znova vklopite, se 30 dni šteje od vklopa, trenutna cena je v tem obdobju že veljala in znižanje ni prikazano.",
        saved: "Varianta je shranjena.",
        deleted: "Varianta je izbrisana.",
        armed: "Sproženih obvestil o zalogi: {count}",
      },
      media: {
        upload: "Naloži sliko",
        kind: "Vrsta",
        kinds: { GALLERY: "Galerija (stran izdelka)", CARD: "Kartica (seznami)", HERO: "Naslovna" },
        alt: "Nadomestno besedilo (alt)",
        file: "Datoteka (JPEG, PNG ali WebP, do 4 MB)",
        moveUp: "Gor",
        moveDown: "Dol",
        delete: "Izbriši",
        saveAlt: "Shrani",
        confirmDelete: "Izbrišem sliko? Datoteka se odstrani in je ni mogoče obnoviti.",
        deleted: "Slika je izbrisana.",
        invalid: "Datoteka ni veljavna slika ali je prevelika.",
        uploaded: "Slika je naložena.",
        empty: "Brez slik.",
      },
      history: { date: "Datum", price: "Cena", compareAt: "Primerjalna", empty: "Brez zapisov." },
      restock: {
        intro: "Prijave na obvestilo »Obvestite me« za ta izdelek.",
        pending: "Čakajo na potrditev",
        confirmed: "Potrjene",
        notified: "Že obveščene",
        unsubscribed: "Odjavljene",
        armable: "Pripravljene za pošiljanje",
        send: "Pošlji obvestila zdaj",
        sendHint: "Sproži obvestilo vsem potrjenim prijavam, ki še niso bile obveščene, če je izdelek na zalogi.",
        sent: "Sproženo: {armed} · poslano: {sent} · neuspešno: {failed}",
        noStock: "Izdelek ni na zalogi — obvestil ni mogoče poslati.",
      },
      collections: { hint: "Označene kolekcije vsebujejo ta izdelek; vrstni red uredite v kolekciji.", saved: "Kolekcije so posodobljene." },
    },
    collections: {
      title: "Kolekcije",
      newTitle: "Nova kolekcija",
      create: "Ustvari",
      columns: { title: "Naziv", slug: "Slug", products: "Izdelkov", noindex: "Noindex", updated: "Spremenjena" },
      empty: "Ni kolekcij.",
      editor: {
        back: "← Vse kolekcije",
        fields: { title: "Naziv", slug: "Slug (URL)", seoTitle: "SEO naslov", seoDescription: "SEO opis", noindex: "Ne indeksiraj (noindex)", hideBannerText: "Skrij besedilo na pasici" },
        save: "Shrani kolekcijo",
        saved: "Kolekcija je shranjena.",
        delete: "Izbriši kolekcijo",
        confirmDelete: "Izbrišem kolekcijo? Izdelki ostanejo v katalogu.",
        banner: "Pasica (namizje)",
        bannerMobile: "Pasica (mobilno)",
        uploadBanner: "Naloži",
        removeBanner: "Odstrani",
        products: "Izdelki v kolekciji (vrstni red = prikaz)",
        addProduct: "Dodaj izdelek",
        add: "Dodaj",
        remove: "Odstrani",
        up: "Gor",
        down: "Dol",
        empty: "Kolekcija je prazna.",
        slugTaken: "Slug je že v uporabi.",
        invalid: "Preverite vnesene podatke.",
      },
    },
    bundles: {
      title: "Paketi",
      intro: "Fiksni paketi: sestavine s količinami in cena paketa. Ob nakupu se zaloga odšteje sestavinam, paketi imajo omejitev 1 kos na naročilo.",
      newTitle: "Nov paket",
      chooseProduct: "Izdelek, ki postane paket",
      create: "Ustvari paket",
      columns: { title: "Naziv", price: "Cena paketa", value: "Vrednost sestavin", savings: "Prihranek", active: "Aktiven", components: "Sestavine" },
      empty: "Ni paketov.",
      editor: {
        back: "← Vsi paketi",
        price: "Cena paketa (centi, z DDV)",
        active: "Aktiven",
        components: "Sestavine",
        variant: "Varianta",
        quantity: "Količina",
        add: "Dodaj sestavino",
        remove: "Odstrani",
        save: "Shrani paket",
        saved: "Paket je shranjen.",
        value: "Vrednost sestavin: {value}",
        savings: "Prihranek: {savings} ({percent} %)",
        omnibusNote: "Prihranek primerja ceno paketa s seštevkom trenutnih cen sestavin; ne izračuna se iz zgodovine cen (Omnibus).",
        invalid: "Preverite sestavine in ceno.",
      },
    },
  },
  coupons: {
    title: "Kuponi",
    intro: "Kode za popust: ena koda na naročilo, brez seštevanja; paketi in že znižani izdelki so izvzeti iz osnove. Povezava /koda/KODA kodo samodejno uveljavi v košarici.",
    newTitle: "Nov kupon",
    create: "Ustvari kupon",
    searchLabel: "Iskanje (koda)",
    activeFilter: "Stanje",
    activeOptions: { all: "Vsi", active: "Aktivni", inactive: "Neaktivni" },
    columns: { code: "Koda", type: "Vrsta", value: "Vrednost", usage: "Uporabe", window: "Veljavnost", active: "Aktiven", redemptions: "Unovčenja" },
    empty: "Ni kuponov za izbrane filtre.",
    types: {
      PERCENT: "Odstotek popusta",
      FIXED: "Znesek na naročilo",
      FIXED_PRODUCT: "Znesek na en izdelek",
      FREE_SHIPPING: "Brezplačna dostava",
      BXGY: "Kupi X, dobi Y (faza 8)",
    },
    editor: {
      back: "← Vsi kuponi",
      sections: { basics: "Osnovno", limits: "Omejitve in veljavnost", eligibility: "Upravičenost", link: "Povezava in QR koda", redemptions: "Unovčenja" },
      fields: {
        code: "Koda",
        type: "Vrsta",
        percentOff: "Popust (%)",
        amountOffCents: "Znesek popusta (centi)",
        active: "Aktiven",
        usageLimitTotal: "Največ uporab skupaj",
        usageLimitPerCustomer: "Največ uporab na kupca",
        startsAt: "Velja od",
        endsAt: "Velja do",
        minSpendCents: "Najmanjši znesek naročila (centi)",
        eligibleProducts: "Velja za izdelke",
        eligibleCollections: "Velja za kolekcije",
        eligibleEmails: "Velja za e-naslove",
        excludedProducts: "Izvzeti izdelki",
      },
      hints: {
        unlimited: "Prazno = brez omejitve.",
        allProducts: "Nič izbranega = vsi izdelki.",
        emails: "En e-naslov na vrstico; prazno = vsi kupci.",
        stacking: "Kode se ne seštevajo (ena na naročilo); paketi in že znižani izdelki so izvzeti iz osnove za popust; dostava ni vključena v odstotek.",
      },
      save: "Shrani kupon",
      saved: "Kupon je shranjen.",
      invalid: "Preverite vnesene podatke (odstotek 1–100, znesek za zneskovne kupone, konec po začetku).",
      codeTaken: "Koda že obstaja.",
      codeInvalid: "Koda »{code}« ni veljavna: 3–24 znakov, samo črke A–Z (brez šumnikov), številke in vezaj, ki ne sme biti prvi znak.",
      delete: "Izbriši kupon",
      confirmDelete: "Izbrišem kupon? Neunovčeni kupon izgine brez sledi.",
      used: "Kupon je bil že unovčen — namesto brisanja ga deaktivirajte.",
      usedCount: "Uporab: {used}",
      linkLabel: "Povezava za samodejno uveljavitev v košarici",
      copy: "Kopiraj povezavo",
      copied: "Kopirano.",
      qrDownload: "Prenesi QR (SVG)",
      qrAlt: "QR koda za kupon {code}",
      qrHint: "QR koda vodi na povezavo zgoraj; primerna je za tisk na vložne listke in embalažo.",
      redemptionsEmpty: "Kupon še ni bil unovčen.",
      redemptionColumns: { order: "Naročilo", email: "E-pošta", total: "Znesek", date: "Datum" },
    },
  },
  settings: {
    title: "Nastavitve",
    intro: "Vse, kar trgovina bere kot nastavitev: dostava in sledenje, DDV in račun, merjenje, SEO, privolitve, vzdrževanje in podpora. Spremembe veljajo takoj, brez uvajanja.",
    cards: {
      shipping: { title: "Dostava in sledenje", body: "Načini dostave po državah, prag brezplačne dostave, predloge povezav za sledenje." },
      tax: { title: "Davki, računi in plačila", body: "Stopnja DDV, podatki podjetja na računu, noga računa, stanje ponudnikov plačil." },
      marketing: { title: "Trženje, SEO, privolitve in trgovina", body: "Merilni ID-ji, Search Console, SEO privzete vrednosti, pasica piškotkov, pravne poti, vzdrževalni način." },
      support: { title: "Podpora", body: "Naslova za podporo in skladnost, delovni čas in obljuba odziva na strani Kontakt." },
    },
    common: { save: "Shrani", saved: "Nastavitve so shranjene.", invalid: "Preverite vnesene podatke." },
    shipping: {
      title: "Dostava in sledenje",
      methods: {
        title: "Načini dostave",
        hint: "Vsak način velja za izbrane države; blagajna ponudi samo načine za državo naslova. Cene so v centih z DDV.",
        columns: { id: "Oznaka (id)", carrier: "Prevoznik", label: "Napis na blagajni", price: "Cena (centi)", estimate: "Rok dostave", countries: "Države" },
        add: "Dodaj način",
        remove: "Odstrani",
        up: "Gor",
        down: "Dol",
        invalid: "Preverite načine (oznake so unikatne male črke in vezaji, cene cela števila, vsaj ena država).",
      },
      thresholds: { title: "Pragovi", freeThreshold: "Brezplačna dostava od (centi z DDV)", standardCost: "Ocena stroška dostave v košarici (centi)" },
      tracking: {
        title: "Predloge povezav za sledenje",
        hint: "https naslov z oznako {number}, ki jo nadomesti številka pošiljke; prazno polje pomeni, da se številka prikaže brez povezave.",
        fields: { ps: "Pošta Slovenije", gls: "GLS" },
        invalid: "Predloga mora biti https naslov brez gesla in vsebovati {number}.",
      },
    },
    tax: {
      title: "Davki, računi in plačila",
      vat: { title: "DDV", rate: "Stopnja DDV (%, celo število)", hint: "Velja za nove ponudbe in naročila; obstoječa naročila in računi hranijo svoj posnetek." },
      company: {
        title: "Podatki podjetja (na računu, v nogi in v strukturiranih podatkih)",
        fields: { name: "Naziv", address: "Naslov", registrationNumber: "Matična številka", vatId: "ID za DDV", email: "Kontaktni e-naslov", phone: "Telefon (neobvezno)" },
        phoneHint: "Prikazan v nogi, na vzorčnem obrazcu za odstop, na računu in v potrditvi naročila. Prazno = ni prikazan.",
        /** Gate G4: the seed writes placeholders (prisma/seed.ts); real data must replace them before launch. */
        placeholderWarning: "Podatki podjetja še vsebujejo začasne vrednosti iz začetnih podatkov. Pred zagonom jih zamenjajte z registriranimi podatki, sicer bodo na računih in v nogi napačni.",
        placeholderFields: { registrationNumber: "matična številka", vatId: "ID za DDV", address: "naslov" },
      },
      invoice: {
        title: "Račun",
        numbering: "Številka računa je enaka številki naročila (NS-LLLL-NNNNN); zaporedje določa trgovina in ga ni mogoče spreminjati.",
        footer: "Dodatna vrstica v nogi računa (neobvezno)",
      },
      providers: {
        title: "Ponudniki plačil",
        hint: "Ključi in skrivnosti ostanejo v okolju strežnika (.env); tukaj je prikazano samo, ali so nastavljeni. Denarnice (Apple Pay, Google Pay) vklopite v nadzorni plošči Stripe.",
        names: { stripe: "Stripe (kartice, Apple Pay, Google Pay, Klarna)", paypal: "PayPal", test: "Testni ponudnik (samo v testnem načinu)" },
        configured: "Nastavljeno",
        missing: "Ni nastavljeno",
        present: "prisotno",
        absent: "manjka",
      },
    },
    marketing: {
      title: "Trženje, SEO, privolitve in trgovina",
      analytics: {
        title: "Merilni ID-ji",
        hint: "Naloži se samo Google Tag Manager, in to šele po privolitvi za analitiko ali trženje; Google Consent Mode v vsebniku loči obe kategoriji. Oznake, ki ne upoštevajo Consent Mode (npr. Meta, TikTok), morajo v GTM zahtevati ad_storage ali se sprožiti na dogodek nasmeh_consent z marketing = true. Ostali ID-ji se hranijo za fazo 8 in so vezani na navedeno kategorijo privolitve.",
        fields: { gtmId: "Google Tag Manager (GTM-…)", ga4Id: "Google Analytics 4 (G-…)", metaPixelId: "Meta Pixel (številka)", tiktokPixelId: "TikTok Pixel" },
        categories: { gtmId: "analitika ali trženje", ga4Id: "analitika", metaPixelId: "trženje", tiktokPixelId: "trženje" },
        categoryLabel: "kategorija privolitve",
        invalid: "Preverite obliko ID-jev (GTM-XXXX, G-XXXX, Meta samo številke).",
      },
      verification: { title: "Google Search Console", token: "Koda za potrditev lastništva (vsebina meta oznake)" },
      seo: {
        title: "SEO privzete vrednosti",
        fields: { titleTemplate: "Predloga naslova (%s = naslov strani)", description: "Privzeti opis (prazno = opis iz besedil)", indexable: "Iskalniki smejo indeksirati trgovino" },
        indexHint: "Izklop doda noindex na vse strani in v robots.txt prepove vse; uporabite pred zagonom ali za predogled.",
        invalid: "Predloga naslova mora vsebovati %s.",
      },
      consent: {
        title: "Privolitve (piškotki)",
        version: "Trenutna različica privolitve: {version}",
        bump: "Zahtevaj novo privolitev",
        bumpHint: "Poveča različico; vsi obiskovalci ob naslednjem obisku znova vidijo pasico. Uporabite, ko se spremeni tabela piškotkov ali namen.",
        confirmBump: "Zahtevam novo privolitev od vseh obiskovalcev?",
        bumped: "Nova različica privolitve: {version}.",
        banner: { title: "Naslov pasice (prazno = privzeto besedilo)", body: "Besedilo pasice (prazno = privzeto besedilo)" },
        cookies: {
          title: "Tabela piškotkov (prikazana na strani Politika piškotkov)",
          columns: { name: "Ime", provider: "Ponudnik", purpose: "Namen", duration: "Trajanje", category: "Kategorija" },
          categories: { necessary: "Nujni", analytics: "Analitični", marketing: "Trženjski" },
          add: "Dodaj piškotek",
          remove: "Odstrani",
        },
        invalid: "Preverite vrstice tabele (vsa polja so obvezna).",
      },
      legal: {
        title: "Pravne strani",
        hint: "Poti do pravnih strani, ki jih uporabljajo blagajna, pasica piškotkov ter obrazci za kontakt, odstop od pogodbe in prijavo neželenega učinka; noga uporablja meni Noga — Pravno.",
        fields: { terms: "Pogoji poslovanja", privacy: "Politika zasebnosti", cookies: "Politika piškotkov", withdrawal: "Odstop od pogodbe" },
        invalid: "Poti morajo biti relativne (/stran).",
      },
      maintenance: {
        title: "Vzdrževalni način",
        fields: { enabled: "Trgovina je zaklenjena z geslom", password: "Novo geslo za dostop (prazno = ohrani obstoječe; najmanj 4 znaki)", message: "Sporočilo obiskovalcem (neobvezno)" },
        hasPassword: "Geslo je nastavljeno (shranjeno kot zgoščena vrednost, ne v čistopisu).",
        noPassword: "Geslo še ni nastavljeno; brez njega trgovine ni mogoče zakleniti.",
        hint: "Skrbništvo in prijava ostaneta dostopna; kupci vidijo stran z geslom, dokler ne vnesejo gesla.",
        invalid: "Zaklenjena trgovina potrebuje geslo (4–80 znakov).",
      },
    },
    support: {
      title: "Podpora",
      hint: "Naslova prejemata sporočila obrazcev (podpora vse teme, skladnost prijave neželenih učinkov); delovni čas in obljuba odziva se prikažeta na strani Kontakt.",
      fields: { supportEmail: "E-naslov podpore", complianceEmail: "E-naslov za skladnost", hours: "Delovni čas", responseTime: "Obljuba odziva" },
      invalid: "Preverite e-naslova in besedili.",
    },
  },
  content: {
    title: "Vsebina",
    intro: "Domača stran, oglasna vrstica, pozdravno okno in sestavljanje paketa tukaj; strani, navigacija, mediji in e-poštne predloge imajo svoje zaslone.",
    cards: {
      home: { title: "Domača stran", body: "Vrstni red in vidnost odsekov, hero, pasica paketov, pasica rutine." },
      marquee: { title: "Oglasna vrstica", body: "Besedilo, povezava in vklop vrstice nad glavo strani." },
      popup: { title: "Pozdravno okno", body: "Koda, zamik, besedila in vklop pozdravnega okna z e-novicami." },
      bundle: { title: "Sestavljanje paketa", body: "Količine v ponudbi, dodatki, koda kupona in vrstica za mesečno dostavo." },
      pages: { title: "Strani", body: "Pravne in vsebinske strani s predlogo, SEO in objavo." },
      menus: { title: "Navigacija", body: "Glavni meni, mobilni predal, pripomočna vrstica in stolpci noge." },
      media: { title: "Mediji", body: "Knjižnica slik za hero, pasice in strani." },
      email: { title: "E-poštne predloge", body: "Zadeve in besedila transakcijskih sporočil s testnim pošiljanjem." },
    },
    home: {
      title: "Domača stran",
      sections: {
        title: "Odseki",
        hint: "Vrstni red tukaj je vrstni red na strani; skriti odseki se ne izpišejo.",
        names: { hero: "Hero (uvodni odsek)", rail: "Naše uspešnice", bundleBanner: "Pasica paketov", routineBanner: "Pasica rutine" },
        visible: "Viden",
        up: "Gor",
        down: "Dol",
        save: "Shrani vrstni red",
        saved: "Vrstni red je shranjen.",
      },
      hero: {
        title: "Hero",
        fields: {
          kicker: "Oznaka nad naslovom", title: "Naslov", subtitle: "Podnaslov", footnote: "Opomba pod podnaslovom (živo besedilo)", ctaLabel: "Gumb — napis", ctaHref: "Gumb — povezava",
          videoDesktop: "Video (namizje) — pot ali URL", videoMobile: "Video (mobilno) — pot ali URL", poster: "Slika / poster",
          imageAlt: "Nadomestno besedilo slike", promoOverlayText: "Promocijska vrstica — besedilo", promoOverlayHref: "Promocijska vrstica — povezava",
        },
        mediaHint: "Izberite iz knjižnice medijev ali vpišite pot (/uploads/…) oziroma https URL.",
        /** Hero videos come only from the store's own origin: the content security policy blocks other media hosts (QA M13). */
        videoHint: "Naložite video MP4 ali WebM v knjižnico medijev in ga izberite tukaj (pot /uploads/…). Samo mobilni video se predvaja le na telefonih.",
        videoExternal: "Video mora biti datoteka iz knjižnice medijev (pot /uploads/…): zunanjih video naslovov brskalnik zaradi varnostne politike trgovine ne predvaja.",
        footnoteHint: "Navedba, označena z * ali ^ (v oznaki nad naslovom, naslovu, podnaslovu, napisu gumba ali promocijski vrstici), potrebuje opombo, ki jo pojasni (npr. da se rezultati razlikujejo od osebe do osebe). Samo navadno besedilo, do 300 znakov.",
        footnoteMissing: "Besedilo v heroju vsebuje oznako * ali ^, opomba pa je prazna — hero se ne shrani, dokler opombe ne izpolnite.",
        save: "Shrani hero",
        saved: "Hero je shranjen.",
      },
      bundleBanner: { title: "Pasica paketov", fields: { title: "Naslov", cta: "Povezava — napis", href: "Povezava" }, save: "Shrani pasico", saved: "Pasica je shranjena." },
      routineBanner: {
        title: "Pasica rutine",
        fields: { title: "Naslov (dostopnost)", href: "Povezava", image: "Slika (pot ali URL)", imageAlt: "Nadomestno besedilo", footnote: "Opomba pod sliko (živo besedilo)" },
        save: "Shrani pasico",
        saved: "Pasica je shranjena.",
      },
      invalid: "Preverite vnesene podatke (povezave so relativne poti ali https naslovi).",
    },
    marquee: {
      title: "Oglasna vrstica",
      fields: { text: "Besedilo", href: "Povezava (neobvezno)", active: "Vrstica je vklopljena" },
      save: "Shrani vrstico",
      saved: "Oglasna vrstica je shranjena.",
      invalid: "Preverite besedilo in povezavo.",
    },
    popup: {
      title: "Pozdravno okno",
      intro: "Okno se odpre po zamiku, razen v košarici, na blagajni, v računu, pri prijavi, registraciji in ponastavitvi gesla, na straneh za potrditev, odjavo in oceno, na obrazcih za kontakt, odstop od pogodbe, reklamacijo, neželeni učinek in sledenje ter prijavljenim potrjenim naročnikom. Gostu se ne prikaže, dokler ima brskalnik shranjeno kodo iz okna (do uporabe kode ali druge kode iz povezave). Koda mora obstajati med kuponi.",
      fields: {
        active: "Okno je vklopljeno", delaySeconds: "Zamik (sekunde)", couponCode: "Koda kupona", title: "Naslov", body: "Besedilo",
        cta: "Gumb", thankYouTitle: "Zahvala — naslov", thankYouBody: "Zahvala — besedilo",
      },
      save: "Shrani okno",
      saved: "Pozdravno okno je shranjeno.",
      invalid: "Preverite vnesene podatke (zamik 0–600 s, koda kot pri kuponih).",
      couponUnknown: "Koda ne obstaja med aktivnimi kuponi; najprej jo ustvarite v Kuponih.",
    },
    bundle: {
      title: "Sestavljanje paketa",
      intro: "Stran /sestavi-paket se odpre, ko kupec s strani izdelka doda izdelek v košarico. Ponudbe so količine tistega istega izdelka (1, 2 ali 3 kosi) — ločenih izdelkov ali paketnih šifer ni in jih ni treba ustvarjati. Cene, prihranki in odstotki se izračunajo ob vsakem obisku iz cen variant in odločitve promocijskega motorja, zato jih tukaj ni mogoče vpisati. Vrstica s popustom se prikaže samo, kadar je spodaj vpisana koda kupona; isti kupon obračuna tudi blagajna.",
      fields: {
        enabled: "S strani izdelka vodi na sestavljanje paketa",
        subscriptionRow: "Prikaži vrstico za mesečno dostavo",
        offerUnits: "Količine v ponudbi",
        addOnSlugs: "Dodatki — slugi izdelkov",
        couponCode: "Koda kupona",
      },
      hints: {
        enabled: "Izklop odstrani samo preusmeritev s strani izdelka; naslov /sestavi-paket ostane dosegljiv.",
        subscriptionRow: "Vrstica samo zbira zanimanje za mesečno dostavo: nima odstotka, ne spremeni nobenega zneska in se ne pošlje v košarico.",
        offerUnits: "Od ena do štiri števila, ločena z vejico; prvo mora biti 1. Vsako je število kosov izdelka, s katerega je kupec prišel.",
        addOnSlugs: "Do trije slugi, ločeni z vejico. Prazno pomeni, da dodatke izbere trgovina sama iz kolekcij osnovnega izdelka.",
        couponCode: "Prazno pomeni brez popusta. Vpisana koda mora obstajati med aktivnimi kuponi in biti odstotkovna (PERCENT), sicer bi blagajna zaračunala drugače, kot je pokazala stran.",
      },
      save: "Shrani sestavljanje paketa",
      saved: "Sestavljanje paketa je shranjeno.",
      invalid: "Preverite vnesene podatke (prvo število mora biti 1, največ štiri količine in trije slugi).",
      couponUnknown: "Koda ne obstaja med aktivnimi odstotkovnimi kuponi; najprej jo ustvarite v Kuponih.",
      productUnknown: "Vsaj en slug ne pripada aktivnemu izdelku; preverite ga med Izdelki.",
    },
    pages: {
      title: "Strani",
      newTitle: "Nova stran",
      create: "Ustvari stran",
      columns: { title: "Naslov", slug: "Slug", template: "Predloga", published: "Objavljena", reviewed: "Pregledana", updated: "Spremenjena" },
      empty: "Ni strani.",
      templates: { DEFAULT: "Privzeta", LEGAL: "Pravna (z opozorilom o osnutku)", CONTACT: "Kontakt (z gumbom za obrazec)", LANDING: "Pristajalna (široka)" },
      editor: {
        back: "← Vse strani",
        view: "Poglej na strani",
        fields: {
          title: "Naslov", slug: "Slug (URL)", template: "Predloga", body: "Vsebina (HTML)", seoTitle: "SEO naslov", seoDescription: "SEO opis",
          published: "Objavljena", reviewed: "Pravno pregledana",
        },
        reviewedHint: "Pravne strani brez pregleda prikažejo opozorilo o osnutku (D4). Oznaka velja za shranjeno besedilo: sprememba naslova, vsebine ali predloge jo odstrani, znova jo označite ob shranjevanju nespremenjenega besedila.",
        shadowedHint: "Ta slug ima vgrajeno stran, ki prikaže to vsebino v svoji predlogi.",
        lockedHint: "Pravna stran: slug je zaklenjen, ker nanj vodijo noga, blagajna, obrazci ali pravne povezave v nastavitvah. Strani ni mogoče izbrisati, objavo pa lahko umaknete.",
        templateLockedHint: "Pravna stran obdrži pravno predlogo, ki do pregleda prikazuje opozorilo o osnutku.",
        slugLocked: "Slug in pravna predloga te strani sta zaklenjena: nanjo vodijo noga, blagajna in obrazci.",
        confirmUnpublishLegal: "Umaknem objavo pravne strani? Povezave v nogi, na blagajni in v obrazcih bodo vračale 404, dokler strani znova ne objavite.",
        savedReviewCleared: "Stran je shranjena, oznaka pravnega pregleda pa ne: besedilo se je spremenilo. Ko je novo besedilo pregledano, jo označite in stran znova shranite.",
        preview: "Predogled shranjene vsebine",
        previewEmpty: "Shranite vsebino, da se prikaže predogled.",
        save: "Shrani stran",
        saved: "Stran je shranjena.",
        invalid: "Preverite vnesene podatke.",
        slugTaken: "Slug je že v uporabi.",
        slugReserved: "Ta naslov pripada vgrajeni strani trgovine.",
        delete: "Izbriši stran",
        confirmDelete: "Izbrišem stran? Povezave nanjo bodo vrnile 404.",
        deleteProtected: "Te strani ni mogoče izbrisati: je pravna stran, na katero vodijo vgrajene poti, noga, blagajna ali obrazci. Namesto tega umaknite objavo.",
      },
    },
    /**
     * Operator links to a product page that answers 404 (QA 2026-09-30 v-a): the product is a draft,
     * archived, a hidden deal SKU or a withdrawn bundle. The storefront leaves such a link out, so the
     * editors name it; {links} is a list of "link (reason)".
     */
    links: {
      reasons: { unknown: "izdelek ne obstaja", draft: "osnutek", archived: "arhiviran", hiddenDeal: "skriti akcijski SKU", bundleInactive: "paket ni vklopljen" },
      menu: "Te povezave vodijo na izdelke, ki niso naprodaj, zato jih trgovina ne prikaže, dokler izdelek ni znova naprodaj: {links}.",
      /** Stored featured cards on load; unlike a link, the save refuses them (menus.editor.featuredUnknown). {slugs}: "slug (reason)". */
      featured: "Predstavljeni izdelki niso več naprodaj, zato jih glava ne prikaže: {slugs}. Meni se ne bo shranil, dokler jih ne odstranite ali izdelka znova ponudite v prodajo.",
      hero: "Te povezave vodijo na izdelke, ki niso naprodaj: {links}. Dokler izdelek ni znova naprodaj, gumb vodi v trgovino, promocijske vrstice pa trgovina ne prikaže.",
      banner: "Povezava vodi na izdelek, ki ni naprodaj: {links}. Dokler izdelek ni znova naprodaj, trgovina te pasice ne prikaže.",
      marquee: "Povezava vodi na izdelek, ki ni naprodaj: {links}. Dokler izdelek ni znova naprodaj, je vrstica prikazana brez povezave.",
      /** After a product or bundle save that took it off sale or renamed it; {places} from `places` and menus.handles. */
      product: "Na stran izdelka, ki zdaj vrne 404 (izdelek ni naprodaj ali ima nov slug), še vodijo povezave v: {places}. Trgovina jih ne prikaže (gumb v heroju vodi v trgovino); popravite ali odstranite jih v Navigaciji oziroma Vsebini.",
      places: { hero: "Domača stran — hero", bundleBanner: "Domača stran — pasica paketov", routineBanner: "Domača stran — pasica rutine", marquee: "Oglasna vrstica" },
    },
    menus: {
      title: "Navigacija",
      intro: "Meniji so podatki: glava, mobilni predal, pripomočna vrstica in stolpci noge se preberejo ob vsakem prikazu.",
      columns: { handle: "Meni", title: "Naziv", items: "Elementov", updated: "Spremenjen" },
      handles: {
        header: "Glavni meni (glava)", utility: "Pripomočna vrstica", "footer-trgovina": "Noga — Trgovina", "footer-pomoc": "Noga — Podpora",
        "footer-sledite": "Noga — Sledite nam", "footer-pravno": "Noga — Pravno", mobile: "Mobilni predal",
      },
      editor: {
        back: "← Vsi meniji",
        menuTitle: "Naziv menija",
        /** Footer columns show the menu title (QA T7-F3); the seeded admin label keeps the default heading. */
        menuTitleHint: "Pri stolpcih noge je naziv menija naslov stolpca v trgovini. Privzeti naziv (»Noga — …«) pomeni privzeti naslov stolpca.",
        item: "Element",
        label: "Napis",
        href: "Povezava",
        color: "Slog",
        colors: { "": "Običajno", sale: "Akcija (ikona popusta)" },
        children: "Podelementi (spustni meni)",
        featured: "Predstavljeni izdelki (slugi, ločeni z vejico; največ 2)",
        featuredHint: "Velja za glavni meni in mobilni predal: kartici z naslovom in sliko izdelka. Slug mora pripadati izdelku, ki je naprodaj: aktivnemu, ki ni skriti akcijski SKU, pri paketu pa mora biti paket vklopljen.",
        /** {slugs}: each refused slug with its reason from content.links.reasons (QA v-a). */
        featuredUnknown: "Predstavljeni izdelki niso naprodaj, zato jih glava ne bi prikazala: {slugs}. Popravite slug ali izdelek najprej ponudite v prodajo (status Aktiven, brez oznake skritega akcijskega SKU, paket vklopljen).",
        featuredCount: "Element ima lahko največ 2 predstavljena izdelka. Odvečne sluge odstranite.",
        addItem: "Dodaj element",
        addChild: "Dodaj podelement",
        remove: "Odstrani",
        up: "Gor",
        down: "Dol",
        save: "Shrani meni",
        saved: "Meni je shranjen.",
        invalid: "Preverite napise in povezave (relativne poti ali https naslovi).",
      },
    },
    media: {
      title: "Mediji",
      intro: "Slike za hero, pasice in strani ter video za hero. Slike so pretvorjene v WebP, video (MP4 ali WebM) se shrani tak, kot je; pot kopirajte v polja, kjer jo potrebujete.",
      upload: "Naloži",
      /** One file per request (QA T7-F6): the limits are per file, a selection uploads one after another. */
      file: "Datoteke (slike JPEG, PNG ali WebP do 4 MB; video MP4 ali WebM do 9 MB; do 8 naenkrat, naložijo se ena za drugo)",
      uploading: "Nalagam {current} od {total} …",
      tooLarge: "Datoteka »{name}« je prevelika (slika do 4 MB, video do 9 MB).",
      partial: "Naloženih {done} od {total}. Datoteka »{name}« ni veljavna ali je prevelika.",
      video: "Video",
      confirmDelete: "Izbrišem datoteko iz knjižnice? Datoteka se odstrani in je ni mogoče obnoviti.",
      deleted: "Datoteka je izbrisana.",
      alt: "Nadomestno besedilo (alt)",
      saveAlt: "Shrani alt",
      copy: "Kopiraj pot",
      copied: "Kopirano.",
      delete: "Izbriši",
      references: "Uporab: {count}",
      cannotDelete: "Datoteka je v uporabi — najprej zamenjajte sklice.",
      empty: "Knjižnica je prazna.",
      uploaded: "Datoteke so naložene.",
      invalid: "Datoteka ni veljavna slika ali video oziroma je prevelika.",
    },
    email: {
      title: "E-poštne predloge",
      intro: "Vsako transakcijsko sporočilo ima privzeto besedilo v kodi; prilagojena predloga ga nadomesti pri naslednjem pošiljanju.",
      columns: { template: "Predloga", description: "Kdaj se pošlje", state: "Stanje", updated: "Spremenjena" },
      states: { override: "Prilagojena", default: "Privzeta (koda)" },
      editor: {
        back: "← Vse predloge",
        placeholders: "Razpoložljiva polja",
        placeholderHint: "Polja pišite kot {{ime}}; besedilna polja se ubežijo, pripravljeni HTML bloki se vstavijo taki, kot so.",
        subject: "Zadeva",
        body: "Vsebina (HTML)",
        preview: "Predogled z vzorčnimi podatki",
        testTo: "Testni prejemnik",
        sendTest: "Pošlji test",
        sent: "Testno sporočilo je poslano.",
        sendFailed: "Pošiljanje ni uspelo; preverite SMTP nastavitve.",
        save: "Shrani predlogo",
        saved: "Predloga je shranjena in velja za naslednja sporočila.",
        reset: "Povrni privzeto",
        confirmReset: "Odstranim prilagojeno predlogo? Uporabi se privzeto besedilo iz kode.",
        resetDone: "Privzeta predloga je spet v uporabi.",
        invalid: "Preverite zadevo in vsebino.",
        unknown: "Neznana polja: {names}",
      },
    },
  },
  mfa: {
    title: "Nastavite dvostopenjsko preverjanje",
    intro: "Vsak član ekipe se prijavlja z geslom in kodo iz aplikacije za preverjanje pristnosti (npr. Google Authenticator, 1Password, Aegis). Brez tega skrbništvo ni dostopno.",
    step1: "1. V aplikaciji skenirajte kodo QR ali ročno vnesite ključ.",
    step2: "2. Vnesite 6-mestno kodo, ki jo aplikacija prikaže.",
    secretLabel: "Ročni vnos ključa",
    qrAlt: "Koda QR za aplikacijo za preverjanje pristnosti",
    codeLabel: "Koda iz aplikacije",
    submit: "Potrdi in vklopi",
    invalid: "Koda ni pravilna. Preverite čas na napravi in poskusite znova.",
    rateLimited: "Preveč poskusov. Počakajte nekaj minut.",
    doneTitle: "Dvostopenjsko preverjanje je vklopljeno",
    recoveryTitle: "Rezervne kode",
    recoveryIntro: "Vsaka koda velja enkrat in nadomesti aplikacijo, če izgubite dostop do nje. Shranite jih zdaj — prikazane so samo tokrat.",
    recoveryAck: "Shranil sem kode, nadaljuj",
    genericError: "Nastavitev ni uspela. Osvežite stran in poskusite znova.",
  },
  team: {
    title: "Ekipa",
    intro: "Člani ekipe z vlogami. Lastnik ureja vse; upravitelj katalog, promocije in vsebino; podpora naročila, stranke in ocene; odprema naročila in pošiljke.",
    columns: { name: "Ime", email: "E-pošta", role: "Vloga", mfa: "2FA", sessions: "Seje", actions: "Dejanja" },
    mfaOn: "vklopljeno",
    mfaOff: "čaka na nastavitev",
    sessionsVersion: "različica {version}",
    createTitle: "Dodaj člana",
    nameLabel: "Ime",
    emailLabel: "E-pošta",
    roleLabel: "Vloga",
    create: "Dodaj",
    createdTitle: "Član je dodan",
    createdBody: "Začasno geslo (prikazano samo tokrat): {password}. Ob prvi prijavi bo moral nastaviti dvostopenjsko preverjanje.",
    promotedBody: "Obstoječi račun je dobil vlogo {role}. Ob naslednji prijavi bo moral nastaviti dvostopenjsko preverjanje.",
    changeRole: "Spremeni vlogo",
    revokeSessions: "Odjavi povsod",
    resetMfa: "Ponastavi 2FA",
    demote: "Odstrani iz ekipe",
    selfNote: "Lastnih dovoljenj tu ne morete spreminjati.",
    confirmDemote: "Odstranim člana iz ekipe? Račun ostane, vloga postane Stranka.",
    confirmRoleChange: "Spremenim vlogo člana {name} v {role}? Dovoljenja veljajo takoj.",
    selfEmail: "To je vaš lastni e-poštni naslov; lastne vloge tu ne morete spreminjati.",
    notFound: "Člana ni mogoče najti; stran osvežite.",
    confirmReset: "Ponastavim dvostopenjsko preverjanje? Član ga bo moral znova nastaviti ob prijavi.",
    invalidEmail: "Vnesite veljaven e-poštni naslov.",
    empty: "Ekipa je še prazna.",
  },
  account: {
    title: "Moj račun",
    mfaStatus: "Dvostopenjsko preverjanje",
    mfaSince: "vklopljeno od {date}",
    regenerateTitle: "Nove rezervne kode",
    regenerateIntro: "Stare rezervne kode prenehajo veljati. Vnesite trenutno kodo iz aplikacije.",
    regenerate: "Ustvari nove kode",
    signOutEverywhere: "Odjavi povsod",
    signOutEverywhereHint: "Razveljavi vse vaše seje, tudi to; prijavite se znova.",
    sessionNote: "Skrbniške seje potečejo 12 ur po prijavi.",
  },
} as const;
