/** Adverse-event report form (§12.6, cosmetics vigilance). */
export const adverse = {
  title: "Prijava neželenega učinka",
  description: "Sporočite neželeni učinek ali varnostno vprašanje o izdelku Nasmeh.si ekipi za varnost izdelkov.",
  eyebrow: "Varnost izdelkov",
  intro:
    "Če ste po uporabi izdelka opazili neželeni učinek, nam ga prosimo sporočite. Podatke obravnava ekipa za varnost izdelkov v skladu z Uredbo (ES) št. 1223/2009 o kozmetičnih izdelkih.",
  notEmergency: "Ta obrazec ni nujna medicinska pomoč. Ob resnih težavah se takoj obrnite na zdravnika ali na številko 112.",
  sections: {
    reporter: "1. Prijavitelj",
    product: "2. Izdelek",
    reaction: "3. Neželeni učinek",
    consent: "4. Privolitve",
  },
  reporter: {
    name: "Ime in priimek",
    email: "E-pošta za odgovor",
    phone: "Telefon (neobvezno)",
    type: "Kdo prijavlja?",
    types: {
      USER: "Uporabnik izdelka",
      CARER: "Skrbnik ali sorodnik uporabnika",
      PROFESSIONAL: "Zdravstveni delavec",
    },
  },
  product: {
    select: "Izdelek",
    choose: "Izberite izdelek",
    batch: "Številka serije",
    batchHint: "Natisnjena na embalaži (LOT/serija). Brez nje prijave ne moremo obravnavati.",
    purchasePlace: "Kje ste izdelek kupili?",
    purchaseDate: "Datum nakupa (neobvezno)",
    orderNumber: "Številka naročila (neobvezno)",
    orderNumberHint: "Če ste kupili na Nasmeh.si; e-pošta se mora ujemati z e-pošto ob naročilu.",
  },
  reaction: {
    reasonLabel: "Vrsta prijave",
    reasons: { REACTION: "Opažen neželeni učinek", PRODUCT_SAFETY: "Vprašanje o varnosti izdelka" },
    description: "Opis učinka",
    descriptionHint: "Opišite, kaj ste opazili, kje in kako dolgo po uporabi (vsaj 20 znakov). Ne vpisujte podatkov plačilne kartice.",
    onsetDate: "Datum pojava (neobvezno)",
    ongoing: "Ali učinek še traja?",
    medicalTreatment: "Ste poiskali zdravniško pomoč?",
    medicalDetails: "Podrobnosti zdravniške pomoči (neobvezno)",
    yes: "Da",
    no: "Ne",
    photos: "Fotografije (neobvezno)",
    photosHint: "Fotografija učinka in embalaže s številko serije pomaga pri oceni. Največ 4 fotografije JPG, PNG ali WebP, vsaka do 2 MB.",
  },
  consent: {
    privacy: "Seznanjen/-a sem, da se podatki obdelujejo za oceno varnosti izdelka in izpolnjevanje zakonskih obveznosti proizvajalca.",
    privacyLink: "Preberite politiko zasebnosti",
    contact: "Ekipa za varnost izdelkov me lahko kontaktira z dodatnimi vprašanji (neobvezno).",
  },
  submit: "Pošlji prijavo",
  submitting: "Pošiljamo …",
  success: {
    title: "Prijavo smo prejeli",
    body: "Hvala. Ekipa za varnost izdelkov bo prijavo pregledala; shranite oznako zahtevka.",
    reference: "Oznaka zahtevka",
  },
  errors: {
    invalid: "Preverite vnesene podatke: izdelek, številka serije, opis učinka in privolitev so obvezni.",
    challenge: "Preverjanje ni uspelo. Potrdite, da niste robot, in poskusite znova.",
    orderNotFound: "Naročila s to številko in e-pošto ni mogoče povezati. Pustite polje prazno ali uporabite e-pošto ob naročilu.",
    photos: "Dodajte največ 4 fotografije JPG, PNG ali WebP. Vsaka je lahko velika največ 2 MB.",
    failed: "Prijave ni bilo mogoče poslati. Poskusite znova ali nam pišite po e-pošti.",
    conflict: "Prijava s to oznako je bila že oddana z drugačnimi podatki. Osvežite stran za novo prijavo.",
  },
} as const;
