/** Adverse-event report form (§12.6, cosmetics vigilance). */
export const adverse = {
  title: "Prijava neželenega učinka",
  description: "Sporočite neželeni učinek ali varnostno vprašanje o izdelku Nasmeh.si ekipi za varnost izdelkov.",
  eyebrow: "Varnost izdelkov",
  intro:
    "Če ste po uporabi izdelka opazili neželeni učinek, nam ga prosimo sporočite. Podatke obravnava ekipa za varnost izdelkov v skladu z Uredbo (ES) št. 1223/2009 o kozmetičnih izdelkih.",
  notEmergency: "Ta obrazec ni nujna medicinska pomoč. Ob resnih težavah se takoj obrnite na zdravnika ali na številko 112.",
  sections: {
    reporter: "1. Prijavitelj",
    product: "2. Izdelek",
    reaction: "3. Neželeni učinek",
    consent: "4. Obdelava podatkov",
  },
  reporter: {
    name: "Ime in priimek",
    email: "E-pošta za odgovor",
    phone: "Telefon (neobvezno)",
    type: "Kdo prijavlja?",
    types: {
      USER: "Uporabnik izdelka",
      CARER: "Skrbnik ali sorodnik uporabnika",
      PROFESSIONAL: "Zdravstveni delavec",
    },
  },
  product: {
    select: "Izdelek",
    choose: "Izberite izdelek",
    batch: "Številka serije",
    batchHint: "Natisnjena na embalaži (LOT/serija). Če jo imate, jo vpišite, saj nam močno pomaga pri oceni prijave.",
    batchUnknown: "Številke serije ne poznam (na primer embalaže nimam več)",
    purchasePlace: "Kje ste izdelek kupili?",
    purchaseDate: "Datum nakupa (neobvezno)",
    orderNumber: "Številka naročila (neobvezno)",
    orderNumberHint: "Če ste kupili na Nasmeh.si; e-pošta se mora ujemati z e-pošto ob naročilu.",
  },
  reaction: {
    reasonLabel: "Vrsta prijave",
    reasons: { REACTION: "Opažen neželeni učinek", PRODUCT_SAFETY: "Vprašanje o varnosti izdelka" },
    description: "Opis učinka",
    descriptionHint: "Opišite, kaj ste opazili, kje in kako dolgo po uporabi (vsaj 20 znakov). Ne vpisujte podatkov plačilne kartice.",
    onsetDate: "Datum pojava (neobvezno)",
    ongoing: "Ali učinek še traja?",
    medicalTreatment: "Ste poiskali zdravniško pomoč?",
    medicalDetails: "Podrobnosti zdravniške pomoči (neobvezno)",
    yes: "Da",
    no: "Ne",
    photos: "Fotografije (neobvezno)",
    photosHint: "Fotografija učinka in embalaže s številko serije pomaga pri oceni. Največ 4 fotografije JPG, PNG ali WebP, vsaka do 2 MB.",
  },
  consent: {
    /** Role-neutral until the responsible person under Reg. (EC) 1223/2009 is confirmed; wording changes the ticket's privacy version. */
    privacy: "Seznanjen/-a sem, da se podatki iz prijave, tudi podatki o zdravju, obdelujejo za oceno varnosti izdelka in za izpolnjevanje zakonskih obveznosti glede varnosti kozmetičnih izdelkov.",
    privacyLink: "Preberite politiko zasebnosti",
    contact: "Ekipa za varnost izdelkov me lahko kontaktira z dodatnimi vprašanji (neobvezno).",
  },
  submit: "Pošlji prijavo",
  submitting: "Pošiljamo …",
  success: {
    title: "Prijavo smo prejeli",
    body: "Hvala. Ekipa za varnost izdelkov bo prijavo pregledala; shranite oznako zahtevka.",
    reference: "Oznaka zahtevka",
  },
  errors: {
    invalid: "Preverite vnesene podatke: obvezni so izdelek, številka serije ali potrditev, da je ne poznate, opis učinka in seznanjenost z obdelavo podatkov.",
    /** A server-side refusal names the first field to correct (QA T4-F6); keys are the form field names. */
    fields: {
      name: "Vpišite ime in priimek (2 do 120 znakov).",
      email: "Vpišite veljaven e-poštni naslov za odgovor.",
      phone: "Telefon lahko vsebuje samo številke, presledke in znake + ( ) / - (največ 40 znakov).",
      reporterType: "Izberite, kdo prijavlja.",
      reason: "Izberite vrsto prijave.",
      productSlug: "Izberite izdelek.",
      batchNumber: "Vpišite številko serije (3 do 40 znakov: črke, številke, presledek, pika, poševnica ali vezaj) ali označite, da je ne poznate.",
      purchasePlace: "Vpišite, kje ste izdelek kupili (vsaj 2 znaka).",
      purchaseDate: "Datum nakupa ne sme biti v prihodnosti.",
      orderNumber: "Številka naročila ima obliko NS-2026-00001; če je ne poznate, pustite polje prazno.",
      description: "Opišite učinek z vsaj 20 znaki.",
      onsetDate: "Datum pojava ne sme biti v prihodnosti.",
      ongoing: "Odgovorite, ali učinek še traja.",
      medicalTreatment: "Odgovorite, ali ste poiskali zdravniško pomoč.",
      medicalDetails: "Podrobnosti zdravniške pomoči so predolge (največ 2000 znakov).",
      privacyAccepted: "Potrdite seznanjenost z obdelavo podatkov.",
    },
    challenge: "Preverjanje ni uspelo. Potrdite, da niste robot, in poskusite znova.",
    orderNotFound: "Naročila s to številko in e-pošto ni mogoče povezati. Pustite polje prazno ali uporabite e-pošto ob naročilu.",
    photos: "Dodajte največ 4 fotografije JPG, PNG ali WebP. Vsaka je lahko velika največ 2 MB.",
    failed: "Prijave ni bilo mogoče poslati. Poskusite znova ali nam pišite po e-pošti.",
    conflict: "Prijava s to oznako je bila že oddana z drugačnimi podatki. Osvežite stran za novo prijavo.",
  },
} as const;
