/** Auth surface copy. */
export const auth = {
  botCheck: "Preverjanje ni uspelo. Potrdite, da niste robot, in poskusite znova.",
  social: {
    google: "Z Google",
    facebook: "S Facebookom",
    note: "Socialna prijava kmalu.",
    divider: "Ali",
  },
  login: {
    title: "Prijava",
    subtitle: "Prijavite se z e-pošto in geslom.",
    emailLabel: "E-pošta",
    emailPlaceholder: "ime@primer.si",
    passwordLabel: "Geslo",
    submit: "Prijava",
    forgotLink: "Ste pozabili geslo?",
    registerLink: "Nimate računa? Registrirajte se",
    invalidCredentials: "Napačna e-pošta ali geslo.",
    unverified: "E-pošta še ni potrjena — preverite nabiralnik in kliknite povezavo za potrditev.",
    verifiedOk: "E-pošta je potrjena — prijavite se.",
    resetOk: "Geslo je posodobljeno — prijavite se.",
    genericError: "Prijava ni uspela. Poskusite znova.",
    mfaExpired: "Potrditev prijave je potekla. Prijavite se znova.",
    rateLimited: "Preveč poskusov prijave. Počakajte nekaj minut in poskusite znova.",
  },
  mfa: {
    title: "Potrditvena koda",
    subtitle: "Vnesite 6-mestno kodo iz aplikacije za preverjanje pristnosti ali eno od rezervnih kod.",
    codeLabel: "Koda",
    submit: "Potrdi prijavo",
    invalid: "Koda ni veljavna ali je bila že uporabljena. Poskusite znova.",
    recoveryHint: "Nimate dostopa do aplikacije? Vnesite rezervno kodo (oblika abcde-fghjk); vsaka velja enkrat.",
    backToLogin: "Nazaj na prijavo",
  },
  register: {
    title: "Registracija",
    subtitle: "Ustvarite račun za hitrejši nakup in pregled naročil.",
    firstName: "Ime",
    lastName: "Priimek",
    passwordLabel: "Geslo (vsaj 8 znakov)",
    marketing: "Želim prejemati e-novice in ponudbe (neobvezno).",
    submit: "Ustvari račun",
    loginLink: "Že imate račun? Prijavite se",
    successTitle: "Skoraj gotovo!",
    successBody: "Poslali smo vam potrditveno sporočilo — s klikom na povezavo aktivirate račun.",
    weakPassword: "Geslo mora imeti vsaj 8 znakov.",
    invalidInput: "Preverite ime, e-pošto in geslo. Geslo mora imeti vsaj 8 znakov; predolgo geslo skrajšajte.",
    genericError: "Registracija ni uspela. Poskusite znova.",
  },
  verify: {
    title: "Potrdite e-pošto",
    body: "Za aktivacijo računa potrdite svoj e-poštni naslov.",
    submit: "Potrdi e-pošto",
    requestNew: "Zahtevaj novo povezavo",
    genericError: "Potrditev ni uspela. Poskusite znova.",
    titleOk: "Račun je aktiven 🎉",
    bodyOk: "Vaša e-pošta je potrjena. Prijavite se in nadaljujte z nakupom.",
    titleInvalid: "Povezava ni veljavna",
    bodyInvalid: "Potrditvena povezava je neveljavna ali je potekla. Zahtevajte novo pri registraciji.",
    cta: "Na prijavo",
  },
  forgot: {
    title: "Pozabljeno geslo",
    body: "Vnesite e-pošto in poslali vam bomo povezavo za ponastavitev gesla.",
    submit: "Pošlji povezavo",
    successTitle: "Preverite nabiralnik",
    successBody: "Če račun s to e-pošto obstaja, smo poslali povezavo za ponastavitev (velja 1 uro).",
    backToLogin: "Nazaj na prijavo",
    invalidEmail: "Vnesite veljaven e-poštni naslov.",
    genericError: "Pošiljanje ni uspelo. Poskusite znova.",
  },
  reset: {
    title: "Ponastavitev gesla",
    passwordLabel: "Novo geslo (vsaj 8 znakov)",
    submit: "Shrani novo geslo",
    invalidTitle: "Povezava ni veljavna",
    invalidBody: "Povezava za ponastavitev je neveljavna ali je potekla. Zahtevajte novo.",
    weakPassword: "Geslo mora imeti vsaj 8 znakov.",
    invalidInput: "Preverite povezavo in geslo. Geslo mora imeti vsaj 8 znakov; predolgo geslo skrajšajte.",
    genericError: "Ponastavitev ni uspela. Poskusite znova.",
  },
  logout: "Odjava",
} as const;
