/** Auth surface copy. */
export const auth = {
  botCheck: "Preverjanje ni uspelo. Potrdite, da niste robot, in poskusite znova.",
  /** Labels for the OAuth row of AuthShell, which renders only once a provider is configured (QA 2026-10-03 t3 N4). */
  social: {
    google: "Z Google",
    facebook: "S Facebookom",
    divider: "Ali",
  },
  login: {
    title: "Prijava",
    subtitle: "Prijavite se z e-pošto in geslom.",
    emailLabel: "E-pošta",
    emailPlaceholder: "ime@primer.si",
    passwordLabel: "Geslo",
    submit: "Prijava",
    forgotLink: "Ste pozabili geslo?",
    registerLink: "Nimate računa? Registrirajte se",
    invalidCredentials: "Napačna e-pošta ali geslo.",
    unverified: "E-pošta še ni potrjena — preverite nabiralnik in kliknite povezavo za potrditev.",
    verifiedOk: "E-pošta je potrjena — prijavite se.",
    resetOk: "Geslo je posodobljeno — prijavite se.",
    genericError: "Prijava ni uspela. Poskusite znova.",
    mfaExpired: "Potrditev prijave je potekla. Prijavite se znova.",
    rateLimited: "Preveč poskusov prijave. Počakajte nekaj minut in poskusite znova.",
    /** After a password change from /racun/podatki every session ends, this one too (QA T3-A1). */
    passwordChanged: "Geslo je spremenjeno in odjavljeni ste na vseh napravah. Prijavite se z novim geslom.",
  },
  mfa: {
    title: "Potrditvena koda",
    subtitle: "Vnesite 6-mestno kodo iz aplikacije za preverjanje pristnosti ali eno od rezervnih kod.",
    codeLabel: "Koda",
    submit: "Potrdi prijavo",
    invalid: "Koda ni veljavna ali je bila že uporabljena. Poskusite znova.",
    /** Five wrong codes in five minutes; successful sign-ins do not count (QA 2026-10-03 T4-01). */
    rateLimited: "Preveč napačnih kod. Počakajte nekaj minut in poskusite znova.",
    recoveryHint: "Nimate dostopa do aplikacije? Vnesite rezervno kodo (oblika abcde-fghjk); vsaka velja enkrat.",
    backToLogin: "Nazaj na prijavo",
  },
  register: {
    title: "Registracija",
    subtitle: "Ustvarite račun za hitrejši nakup in pregled naročil.",
    firstName: "Ime",
    lastName: "Priimek",
    passwordLabel: "Geslo (vsaj 8 znakov)",
    marketing: "Želim prejemati e-novice in ponudbe (neobvezno).",
    // Rendered as "<privacyLead> <link>privacyLink</link>." under the checkbox.
    privacyLead: "Kako ravnamo z vašimi osebnimi podatki, pojasnjuje",
    privacyLink: "politika zasebnosti",
    submit: "Ustvari račun",
    loginLink: "Že imate račun? Prijavite se",
    successTitle: "Skoraj gotovo!",
    /** Activation asks for the password chosen here (QA 2026-10-03 T3-02). */
    successBody: "Poslali smo vam potrditveno sporočilo. Odprite povezavo v njem in vnesite geslo, ki ste ga pravkar izbrali — tako aktivirate račun.",
    weakPassword: "Geslo mora imeti vsaj 8 znakov.",
    invalidInput: "Preverite označena polja.",
    /** Per-field messages the server names on an invalid submission (QA T3-F4). */
    fields: {
      firstName: "Vnesite ime (do 60 znakov).",
      lastName: "Vnesite priimek (do 60 znakov).",
      email: "Vnesite veljaven e-poštni naslov (npr. ime@primer.si).",
      password: "Geslo mora imeti od 8 do 72 znakov.",
    },
    genericError: "Registracija ni uspela. Poskusite znova.",
  },
  verify: {
    title: "Potrdite e-pošto",
    /** The link proves the inbox, the password the person who chose it (QA 2026-10-03 T3-02). */
    body: "Za aktivacijo računa vnesite geslo, ki ste ga izbrali ob ustvarjanju računa. Tako preverimo, da račun aktivirate vi.",
    passwordLabel: "Geslo vašega računa",
    /** Shown before the click when confirming the link also confirms the newsletter opt-in chosen with the account. */
    newsletterNote: "Izbrali ste tudi prejemanje e-novic in ponudb: s potrditvijo e-pošte potrdite tudi to prijavo. Prejemanje lahko kadar koli izklopite v razdelku Moj račun.",
    submit: "Potrdi e-pošto",
    requestNew: "Zahtevaj novo povezavo",
    genericError: "Potrditev ni uspela. Poskusite znova.",
    /** Says only that this password does not fit this link; the link stays usable. */
    passwordMismatch: "S tem geslom te povezave ni mogoče potrditi. Vnesite geslo, ki ste ga izbrali ob ustvarjanju računa — če ste se registrirali večkrat, tisto iz registracije, za katero ste prejeli to povezavo. Če gesla ne veste več, se znova registrirajte.",
    rateLimited: "Preveč poskusov. Počakajte nekaj minut in poskusite znova.",
    titleOk: "Račun je aktiven 🎉",
    bodyOk: "Vaša e-pošta je potrjena. Prijavite se in nadaljujte z nakupom.",
    newsletterOk: "Potrjena je tudi vaša prijava na e-novice in ponudbe.",
    titleInvalid: "Povezava ni veljavna",
    bodyInvalid: "Potrditvena povezava je neveljavna ali je potekla. Zahtevajte novo pri registraciji.",
    /** A used link whose account is already verified leads to sign-in, not to a re-registration that sends nothing (QA T3-F5). */
    titleAlreadyActive: "Račun je že aktiven",
    bodyAlreadyActive: "Ta potrditvena povezava je bila že uporabljena in vaš račun je aktiven. Prijavite se; če ste geslo pozabili, ga lahko ponastavite.",
    forgotCta: "Ponastavi geslo",
    cta: "Na prijavo",
  },
  forgot: {
    title: "Pozabljeno geslo",
    body: "Vnesite e-pošto in poslali vam bomo povezavo za ponastavitev gesla.",
    submit: "Pošlji povezavo",
    successTitle: "Preverite nabiralnik",
    successBody: "Če račun s to e-pošto obstaja, smo poslali povezavo za ponastavitev (velja 1 uro).",
    backToLogin: "Nazaj na prijavo",
    invalidEmail: "Vnesite veljaven e-poštni naslov.",
    genericError: "Pošiljanje ni uspelo. Poskusite znova.",
  },
  reset: {
    title: "Ponastavitev gesla",
    passwordLabel: "Novo geslo (vsaj 8 znakov)",
    submit: "Shrani novo geslo",
    invalidTitle: "Povezava ni veljavna",
    invalidBody: "Povezava za ponastavitev je neveljavna ali je potekla. Zahtevajte novo.",
    weakPassword: "Geslo mora imeti vsaj 8 znakov.",
    invalidInput: "Preverite povezavo in geslo. Geslo mora imeti vsaj 8 znakov; predolgo geslo skrajšajte.",
    genericError: "Ponastavitev ni uspela. Poskusite znova.",
  },
  logout: "Odjava",
} as const;
