/** Checkout + orders/confirmation/lookup copy. */
export const checkout = {
  title: "Blagajna",
  steps: {
    contact: "Kontakt",
    shipping: "Dostava",
    payment: "Plačilo",
    review: "Pregled",
  },
  contact: {
    emailLabel: "E-pošta",
    accountHint: "imate račun? prijavite se",
    marketingOptIn: "Želim prejemati e-novice in ponudbe (neobvezno).",
    continue: "Naprej na dostavo",
  },
  shipping: {
    phoneLabel: "Telefon (za kurirja)",
    nameLabel: "Ime in priimek",
    streetLabel: "Ulica",
    streetNumberLabel: "Hišna številka",
    cityLabel: "Kraj",
    postalLabel: "Poštna številka",
    countryLabel: "Država",
    methodLabel: "Način dostave",
    free: "Brezplačna",
    back: "Nazaj",
    continue: "Naprej na plačilo",
  },
  payment: {
    providerLabel: "Način plačila",
    stripe: "Kartica / Apple Pay / Google Pay",
    paypal: "PayPal",
    test: "Testno plačilo (e2e)",
    legalNote: "Z oddajo naročila se strinjate s",
    terms: "pogoji poslovanja",
    and: "in",
    withdrawal: "pravico do odstopa",
    continue: "Na pregled",
  },
  review: {
    title: "Preglejte in potrdite",
    contactLabel: "Kontakt",
    shippingLabel: "Dostava",
    paymentLabel: "Plačilo",
    placeOrder: "Naročilo z obveznostjo plačila",
  },
  pay: {
    title: "Plačilo naročila",
    testSuccess: "Testno plačilo — uspešno",
    testScaFail: "Simuliraj SCA napako",
    testFailure: "Simuliraj neuspeh",
    stripeNotConfigured: "Stripe ni konfiguriran (manjkajo ključi D5).",
    paypalApprove: "Nadaljuj na PayPal",
    failed: "Plačilo ni uspelo. Poskusite znova.",
    processing: "Obdelava …",
    confirm: "Plačaj naročilo",
    retry: "Poskusi znova",
    unavailable: "Plačila trenutno ni mogoče pripraviti. Naročilo je shranjeno; poskusite znova.",
  },
  errors: {
    invalidForm: "Preverite označena polja.",
    emptyCart: "Vaša košarica je prazna.",
    botCheck: "Preverjanje ni uspelo. Poskusite znova.",
    orderFailed: "Naročila ni bilo mogoče ustvariti. Poskusite znova.",
    stock: "Izdelek ni več na zalogi",
    quoteChanged: "Znesek naročila se je spremenil. Preverite novi povzetek in ponovno potrdite.",
    shippingUnavailable: "Za izbrano državo dostava še ni na voljo.",
    noProvider: "Plačila trenutno niso na voljo. Poskusite pozneje.",
  },
  empty: {
    title: "Blagajna",
    body: "Košarica je prazna — najprej dodajte izdelke.",
    cta: "Nazaj v trgovino",
  },
  summary: {
    title: "Povzetek naročila",
    subtotal: "Vmesna vsota",
    shipping: "Dostava",
    shippingNote: "izberite na koraku dostave",
    total: "Skupaj",
    vat: "Vključen DDV",
    updating: "Posodabljamo znesek …",
    klarnaRecap: "ali 3 obroka po",
  },
} as const;

export const orders = {
  confirmation: {
    paidTitle: "Naročilo je potrjeno 🎉",
    paidBody: "Hvala za nakup! Potrditveno sporočilo z računom je že na poti v vaš nabiralnik.",
    pendingTitle: "Čakamo na potrditev plačila",
    pendingBody: "Naročilo je ustvarjeno. Stran se osveži, ko plačilo potrdimo.",
    cancelledTitle: "Naročilo je preklicano",
    cancelledBody: "Naročilo je preklicano. Za dodatne informacije se obrnite na podporo.",
    refundRequiredBody: "Plačilo je bilo prejeto, naročila pa zaradi težave z zalogo ne moremo odpremiti. Vračilo plačila je potrebno; za ureditev se obrnite na podporo.",
    refundedTitle: "Plačilo je vrnjeno",
    refundedBody: "Vračilo plačila za to naročilo je potrjeno.",
    refreshStatus: "Osveži stanje",
    resumePayment: "Nadaljuj plačilo",
    paymentWaiting: "Čakamo na potrditev ponudnika plačil. Stanje se osveži samodejno.",
    checkPaymentStatus: "Preveri stanje plačila",
    paymentCancelled: "Ta poskus plačila je preklican. Za nov poskus nadaljujte na blagajno.",
    newCheckout: "Nazaj na blagajno",
    resumeFailed: "Plačila trenutno ni mogoče nadaljevati. Poskusite znova.",
    orderNumber: "Številka naročila",
    summaryTitle: "Povzetek",
    totalLabel: "Skupaj",
    discountLabel: "Popust",
    deliveryEstimate: "Predviden rok dostave: 2–4 delovni dni.",
    trackingNote: "Ob odpošiljanju boste prejeli e-sporočilo s številko sledenja — pošiljko lahko spremljate na strani Sledi naročilu.",
    createAccountTitle: "Ustvarite račun za naslednjič",
    createAccountBody: "Shranite podatke in spremljajte naročila. Izberite geslo, nato potrdite svoj e-poštni naslov.",
    passwordLabel: "Geslo (vsaj 8 znakov)",
    createAccountCta: "Ustvari račun",
    accountCreated: "Poslali smo vam povezavo za potrditev računa. Pred prijavo potrdite svoj e-poštni naslov.",
    accountErrors: {
      weak_password: "Geslo mora vsebovati od 8 do 72 znakov.",
      order_state: "Račun lahko ustvarite po potrjenem plačilu.",
      order_access: "Dostopa do tega naročila ni mogoče potrditi.",
      email_taken: "Za ta e-poštni naslov račun že obstaja. Prijavite se ali uporabite obnovitev gesla.",
      account_failed: "Potrditvenega sporočila ni bilo mogoče poslati. Poskusite znova.",
    },
    backHome: "Nazaj na domačo stran",
  },
  lookup: {
    title: "Sledi naročilu",
    emailLabel: "E-pošta",
    numberLabel: "Številka naročila (NS-…)",
    submit: "Poišči naročilo",
    notFound: "Naročila s temi podatki ni mogoče najti.",
    statusLabel: "Status",
    methodLabel: "Način dostave",
    trackingLabel: "Sledenje",
    itemsLabel: "Izdelkov",
    totalLabel: "Znesek",
    dateLabel: "Datum",
    statuses: {
      PENDING: "V obdelavi (čaka na plačilo)",
      PAID: "Plačano",
      PROCESSING: "V pripravi",
      SHIPPED: "Odposlano",
      DELIVERED: "Dostavljeno",
      CANCELLED: "Preklicano",
      REFUNDED: "Vrnjeno",
    } as const,
  },
} as const;
