import type { ReasonCode, TopicCode } from "@/lib/support/topics";

export const contact = {
  title: "Kako vam lahko pomagamo?",
  description: "Pišite ekipi Nasmeh.si glede naročila, izdelkov ali drugih vprašanj.",
  eyebrow: "Kontakt",
  intro: "Izberite temo in nam opišite, kaj potrebujete. Odgovor prejmete po e-pošti.",
  channels: { title: "Tu smo za vas", email: "Podpora po e-pošti", compliance: "Varnost izdelkov in skladnost", hours: "Delovni čas", response: "Odgovor na sporočilo" },
  topicTitle: "1. Izberite temo",
  reasonLabel: "Kaj se je zgodilo?",
  topics: {
    TRACKING: { label: "Kje je moje naročilo?", description: "Vprašanje o dostavi ali sledenju." },
    CHANGE: { label: "Sprememba naročila", description: "Naslov, izdelki ali kontaktni podatki." },
    CANCEL: { label: "Preklic naročila", description: "Želite preklicati oddano naročilo." },
    RETURN: { label: "Vračilo izdelkov", description: "Pomoč pri vračilu in naslednjih korakih." },
    WRONG: { label: "Napačni ali manjkajoči izdelki", description: "Vsebina paketa se ne ujema z naročilom." },
    DAMAGED: { label: "Poškodovan izdelek", description: "Poškodba izdelka, embalaže ali iztekanje." },
    ADVICE: { label: "Nasvet o izdelkih", description: "Izbira izdelka ali vprašanje o uporabi." },
    ADVERSE: { label: "Neželeni učinek", description: "Sporočilo ekipi za varnost izdelkov." },
    OTHER: { label: "Drugo vprašanje", description: "Za vse, česar niste našli med temami." },
  } satisfies Record<TopicCode, { label: string; description: string }>,
  reasons: {
    NOT_RECEIVED: "Naročila še nisem prejel/-a",
    TRACKING_UPDATE: "Sledenje se ne posodablja",
    DELIVERY_QUESTION: "Drugo vprašanje o dostavi",
    ADDRESS: "Sprememba naslova za dostavo",
    ITEMS: "Sprememba izdelkov ali količine",
    CONTACT_DETAILS: "Sprememba kontaktnih podatkov",
    CHANGED_MIND: "Premislil/-a sem si",
    ORDERED_BY_MISTAKE: "Naročilo sem oddal/-a pomotoma",
    DELIVERY_DELAY: "Dostava zamuja",
    PURCHASED_ELSEWHERE: "Izdelek sem kupil/-a drugje",
    WRONG_DETAILS: "Vnesel/-la sem napačne podatke",
    MISSING_CODE: "Pozabil/-a sem uporabiti kodo",
    UNSUITABLE: "Izdelek mi ne ustreza",
    RETURN_QUESTION: "Vprašanje o postopku vračila",
    WRONG_ITEM: "Prejel/-a sem napačen izdelek",
    MISSING_ITEM: "Del naročila manjka",
    EXTRA_ITEM: "Prejel/-a sem dodaten izdelek",
    PRODUCT_DAMAGED: "Izdelek je poškodovan",
    PARCEL_DAMAGED: "Paket ali embalaža je poškodovana",
    LEAKING: "Izdelek izteka",
    CHOOSING_PRODUCT: "Pomoč pri izbiri izdelka",
    HOW_TO_USE: "Vprašanje o uporabi",
    PRODUCT_QUESTION: "Drugo vprašanje o izdelku",
    REACTION: "Opažen neželeni učinek",
    PRODUCT_SAFETY: "Vprašanje o varnosti izdelka",
    OTHER: "Drugo",
  } satisfies Record<ReasonCode, string>,
  order: {
    title: "2. Dodajte naročilo (neobvezno)",
    intro: "Naročilo nam pomaga razumeti vaše vprašanje. Sporočilo lahko pošljete tudi brez njega.",
    accountLabel: "Vaše naročilo",
    none: "Brez povezanega naročila",
    accountEmpty: "V vašem računu še ni naročil. Nadaljujete lahko brez povezanega naročila.",
    lookupTitle: "Poiščite svoje naročilo",
    email: "E-pošta ob naročilu",
    number: "Številka naročila",
    numberHint: "Na primer NS-2026-00001. Najdete jo v potrditvi naročila.",
    lookup: "Preveri naročilo",
    looking: "Preverjamo naročilo …",
    linked: "Naročilo je povezano s sporočilom.",
    remove: "Odstrani povezano naročilo",
    statusUnavailable: "Status ni na voljo",
  },
  orderStatuses: { PENDING: "V obdelavi", PAID: "Plačano", PROCESSING: "V pripravi", SHIPPED: "Odposlano", DELIVERED: "Dostavljeno", CANCELLED: "Preklicano", REFUNDED: "Povrnjeno" },
  message: {
    title: "3. Vaše sporočilo",
    name: "Ime in priimek",
    email: "E-pošta za odgovor",
    text: "Kako vam lahko pomagamo?",
    hint: "Opišite vprašanje v 10 do 5.000 znakih. Ne vpisujte gesel ali podatkov plačilne kartice.",
    adverse: "Sporočilo bomo posredovali ekipi za varnost izdelkov. Ta obrazec ni namenjen nujni medicinski pomoči.",
    photos: "Fotografije (neobvezno)",
    photosHint: "Dodajte fotografijo vseh prejetih izdelkov in zunanje embalaže; pri poškodbi tudi fotografijo poškodovanega dela. Največ 4 fotografije JPG, PNG ali WebP, vsaka do 2 MB.",
    privacy: "Seznanjen/-a sem z obdelavo osebnih podatkov za obravnavo tega sporočila.",
    privacyLink: "Preberite politiko zasebnosti",
    submit: "Pošlji sporočilo",
    submitting: "Pošiljamo …",
    chooseTopic: "Pred pošiljanjem izberite temo sporočila.",
  },
  success: {
    title: "Sporočilo smo prejeli",
    body: "Shranite referenco za nadaljnjo komunikacijo. Odgovor boste prejeli na vneseni e-poštni naslov.",
    reference: "Referenca sporočila",
  },
  errors: {
    invalid: "Preverite vnesene podatke, temo in opis sporočila ter potrdite seznanjenost z obdelavo podatkov.",
    challenge: "Preverjanje ni uspelo. Potrdite, da niste robot, in poskusite znova.",
    orderNotFound: "Naročila s temi podatki ni mogoče povezati. Preverite e-pošto in številko naročila ali nadaljujte brez njega.",
    photos: "Dodajte največ 4 fotografije JPG, PNG ali WebP. Vsaka je lahko velika največ 2 MB.",
    failed: "Sporočila ni bilo mogoče poslati. Poskusite znova ali nam pišite po e-pošti.",
    conflict: "Sporočilo s to referenco je bilo že oddano z drugačnimi podatki. Osvežite stran za novo sporočilo.",
  },
} as const;
