export { common } from "./common";
export { home } from "./home";
export { auth } from "./auth";
export { admin } from "./admin";
export { email } from "./email";
export { chrome } from "./chrome";
export { footer } from "./footer";
export { cmp, COOKIES } from "./cmp";
export { newsletter } from "./newsletter";
export { legal } from "./legal";
export { maintenance } from "./maintenance";
export { notFound } from "./notFound";
export { stubs } from "./stubs";
export { catalog } from "./catalog";
export { pdp } from "./pdp";
export { search } from "./search";
export { backInStock } from "./backInStock";
export { cart } from "./cart";
export { checkout, orders } from "./checkout";
export { account } from "./account";
export { reviews } from "./reviews";
export { promo } from "./promo";
export { tracking } from "./tracking";
