/** Reviews copy. */
export const reviews = {
  form: {
    title: "Ocenite izdelek",
    ratingLabel: "Vaša ocena",
    ratingRequired: "Izberite število zvezdic.",
    invalid: "Preverite oceno in dolžino mnenja.",
    invalidLink: "Povezava za oceno ni veljavna ali je potekla.",
    titleLabel: "Naslov mnenja (neobvezno)",
    titlePlaceholder: "V stavku ali dveh",
    textLabel: "Vaše mnenje",
    textPlaceholder: "Kako vam je izdelek ustrezal?",
    photosLabel: "Fotografije (največ 4)",
    photosNote: "JPG, PNG ali WebP, do 2 MB na fotografijo.",
    sensitivityLabel: "Stopnja občutljivosti zob",
    sensitivityOptions: ["Nizka", "Srednja", "Visoka"] as const,
    recommendLabel: "Bi izdelek priporočili?",
    submit: "Oddaj mnenje",
    success: "Hvala za mnenje! Objavljeno bo po pregledu.",
    successAuto: "Hvala za mnenje! Objavljeno je že na strani izdelka.",
    duplicate: "Za ta izdelek ste mnenje že oddali.",
    notEligible: "Mnenje lahko oddate samo za kupljene izdelke.",
    genericError: "Mnenja ni bilo mogoče shraniti. Poskusite znova.",
    photoErrors: {
      count: "Največ 4 fotografije.",
      mime: "Dovoljeni so samo JPG, PNG in WebP.",
      size: "Fotografija je prevelika (največ 2 MB).",
      content: "Fotografije ni mogoče odpreti. Izberite veljavno fotografijo JPG, PNG ali WebP.",
    },
  },
  display: {
    title: "Mnenja kupcev",
    basedOn: "na podlagi",
    reviewsCount: "mnenj",
    distribution: "Porazdelitev ocen",
    photoWall: "Fotografije kupcev",
    sortLabel: "Razvrsti",
    sort: {
      newest: "Najnovejše",
      highest: "Najvišje ocenjene",
      lowest: "Najnižje ocenjene",
    } as const,
    filterStars: "Zvezdice",
    filterPhotos: "S fotografijo",
    allStars: "Vse",
    verified: "Preverjen kupec",
    merchantReply: "Odgovor Nasmeh.si",
    writeCta: "Napiši mnenje",
    writeNote: "Mnenje lahko oddate po nakupu — povezavo najdete v računu ali v e-pošti.",
    empty: "Bodite prvi z mnenjem po nakupu!",
    noMatches: "Za izbrane filtre ni mnenj.",
    customer: "Kupec",
    photoAlt: "Fotografija iz mnenja kupca",
    starsLabel: "zvezdic",
  },
  admin: {
    title: "Moderacija ocen",
    empty: "V čakalni vrsti ni mnenj.",
    product: "Izdelek",
    review: "Mnenje",
    photos: "Fotografije",
    replyLabel: "Odgovor trgovca",
    replyPlaceholder: "Javni odgovor (neobvezno)",
    approve: "Objavi",
    reject: "Zavrni",
    deletePhoto: "Odstrani",
    pending: "Čaka na pregled",
    published: "Objavljeno",
    rejected: "Zavrnjeno",
    saveReply: "Shrani odgovor",
    autoPublishLabel: "Samodejna objava preverjenih mnenj",
    autoPublishOff: "Izklopljeno — vsako mnenje pregleda skrbnik",
    autoPublishFour: "Ocene s 4 ali 5 zvezdicami",
    autoPublishFive: "Samo ocene s 5 zvezdicami",
    delayLabel: "Dni od dostave do povabila k oceni",
    saveSettings: "Shrani nastavitve ocen",
    error: "Spremembe ni bilo mogoče shraniti. Poskusite znova.",
    done: "Shranjeno.",
    filters: { title: "Filtri", product: "Izdelek", rating: "Ocena", photos: "Samo s fotografijami", all: "Vsi", apply: "Filtriraj", reset: "Počisti" },
    verified: "Preverjen nakup",
    unverified: "Nepreverjeno mnenje",
    orderLink: "Naročilo",
  },
} as const;
